"""(xxiv) Roadmap-coverage lint — the DERIVED roadmap bijection + the
record-query manifest (S-ROADMAP 2026-08-31, advisory
validation/ADVISORY_Sroadmap_prompt_2026-08-31.md, addendum F: "certainty
by DERIVATION + LINT, never by reading").

docs/ROADMAP_critical_path.md is GENERATED by tools/roadmap_derive.py
from D6 (phase spine + gate table), the pipeline decision map (via the
assert-gated graph JSON), the choice ledger, the findings registry (OPEN
rows with their `path:` tag), the PROGRESS BLOCCATO table and every phase
mention in docs/atlas/*.md.  This lint makes THREE things machine facts:

  (a) BIJECTION: every D6 phase, every gate G0-G6, every graph node,
      every ledger row, every OPEN finding, every BLOCCATO row, every
      OPEN-CLASS theory object of the claims registry (SCHEMA /
      CONJECTURE — the statements whose completion or falsification is
      still WORK; THEOREM/THEOREM*/PRACTICE are closed statements,
      OUT by class) and every atlas phase mention appears in >= 1 step
      OR carries an explicit OUT:<why>; nothing is silently absent.  A `path: critical` finding
      or BLOCCATO row can NEVER be OUT (the critical path is a filtered
      view of the same table, so an OUT critical object = a hole in the
      path).
  (b) DERIVED-NOT-AUTHORED: the doc on disk equals the in-memory
      regeneration (content hash in the footer + full-text equality) — a
      hand edit or a stale copy after a source change is REJECTED.
  (c) RECORD-QUERY MANIFEST: every path/glob of tools/record_query.py's
      fixed manifest resolves on disk (a moved record file cannot leave
      the navigation tool silently blind).

SEEDED REJECTORS (proven every run, in memory, nothing written):
  - an orphan node PLANTED in the graph with no phase token, no override,
    no OUT rule must make derive() FAIL (Unresolved);
  - a critical finding FORCED to OUT must FAIL;
  - a doctored doc body must be reported STALE;
  - a doctored manifest entry must be reported as a dead path.

Usage:  python tests/test_roadmap_coverage.py     (stdlib-only, < ~2 s)
"""
import glob
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import roadmap_derive as rd          # noqa: E402
import record_query as rq            # noqa: E402


def check_bijection(d):
    v = []
    cover = d['cover']
    placed = {'node': set(), 'ledger': set(), 'finding': set(),
              'bloc': set(), 'gate': set(), 'phase': set(), 'atlas': set()}
    for sid, c in cover.items():
        pid = rd.STEP_BY_ID[sid][1]
        placed['phase'].add(pid)
        placed['gate'].update(c['gates'])
        placed['node'].update(c['nodes'])
        placed['ledger'].update(c['ledger'])
        placed['finding'].update(i for i, _ in c['findings'])
        placed['bloc'].update(i for i, _ in c['bloc'])
        placed['atlas'].update((m['chapter'], m['line'], m['phase'])
                               for m in c['atlas'])
    outs = {(k, i): w for k, i, w in d['outs']}
    for p in rd.PHASES:
        if p not in placed['phase']:
            v.append('phase %s has no step' % p)
    for g in rd.GATES:
        if g not in placed['gate']:
            v.append('gate %s in no step' % g)
    for n in d['nodes']:
        if n['id'] not in placed['node'] and ('node', n['id']) not in outs:
            v.append('node %s neither placed nor OUT' % n['id'])
    for e in d['ledger']:
        if e['id'] not in placed['ledger'] and ('ledger', e['id']) not in outs:
            v.append('ledger %s neither placed nor OUT' % e['id'])
    for e in d['findings']:
        i = e['id']
        if i not in placed['finding'] and ('finding', i) not in outs:
            v.append('finding %s neither placed nor OUT' % i)
        if e.get('path') == 'critical' and i not in placed['finding']:
            v.append('CRITICAL finding %s is OUT — hole in the path' % i)
    for b in d['bloc']:
        i = b['id']
        if i not in placed['bloc'] and ('bloc', i) not in outs:
            v.append('BLOCCATO %s neither placed nor OUT' % i)
        if b.get('path') == 'critical' and i not in placed['bloc']:
            v.append('CRITICAL BLOCCATO %s is OUT — hole in the path' % i)
    placed_claims = set()
    for sid, c in cover.items():
        placed_claims.update(i for i, _ in c.get('claims', []))
    for e in d.get('claims_open', []):
        i = e['id']
        if i not in placed_claims and ('claim', i) not in outs:
            v.append('open claim %s (%s) neither placed nor OUT'
                     % (i, e.get('class')))
    for m in d['atlas']:
        if (m['chapter'], m['line'], m['phase']) not in placed['atlas']:
            v.append('atlas mention %s:%d (%s) in no step'
                     % (m['chapter'], m['line'], m['phase']))
    for k, i, w in d['outs']:
        if not w.startswith('OUT:') or w == 'OUT:UNRESOLVED':
            v.append('%s %s: OUT without a why (%r)' % (k, i, w))
    return v


def check_fresh(text_now):
    try:
        disk = io.open(rd.OUT_DOC, encoding='utf-8').read()
    except OSError:
        return ['ROADMAP doc missing on disk — run tools/roadmap_derive.py']
    v = []
    if rd.stored_hash(disk) != rd.body_hash(disk):
        v.append('ROADMAP footer hash != body hash (hand edit?)')
    if disk != text_now:
        v.append('ROADMAP on disk != regeneration (STALE: a source changed '
                 'or the doc was edited — re-run tools/roadmap_derive.py)')
    return v


def check_manifest(manifest):
    v = []
    for entry in manifest:
        full = os.path.join(ROOT, entry.replace('/', os.sep))
        if any(ch in entry for ch in '*?['):
            if not glob.glob(full):
                v.append('manifest glob %r matches nothing' % entry)
        elif not os.path.isfile(full):
            v.append('manifest path %r does not exist' % entry)
    return v


def seeded_rejectors(d, text_now):
    ok = True
    # 1. planted orphan node
    try:
        rd._UNRES[:] = []
        orphan = {'id': 'SEED-ORPHAN-NODE', 'type': 'nonledger', 'stage': 9,
                  'status': 'OPEN', 'open_duty': 'no window named',
                  'conditions': ''}
        rd.place('node', orphan['id'], orphan, 'no window named', {})
        hit = False
    except rd.Unresolved:
        hit = True
    print('  seeded rejector [planted orphan node]: %s'
          % ('REJECTED (as required)' if hit else 'NOT REJECTED — lint broken'))
    ok &= hit
    # 2. critical finding forced OUT
    d2 = dict(d)
    d2['outs'] = list(d['outs']) + [('finding', 'SEED-CRIT',
                                     'OUT:forced')]
    d2['findings'] = list(d['findings']) + [{'id': 'SEED-CRIT',
                                             'path': 'critical',
                                             'status': 'CONFIRMED'}]
    vs = check_bijection(d2)
    hit = any('CRITICAL finding SEED-CRIT' in t for t in vs)
    print('  seeded rejector [critical finding forced OUT]: %s'
          % ('REJECTED (as required)' if hit else 'NOT REJECTED — lint broken'))
    ok &= hit
    # 3. doctored doc body
    doctored = text_now.replace('## 1. Steps', '## 1. Steps (edited by hand)')
    hit = rd.stored_hash(doctored) != rd.body_hash(doctored)
    print('  seeded rejector [doctored ROADMAP body]: %s'
          % ('REJECTED (as required)' if hit else 'NOT REJECTED — lint broken'))
    ok &= hit
    # 4. doctored manifest
    vs = check_manifest(list(rq.MANIFEST) + ['docs/no_such_record_zzqx.md'])
    hit = any('does not exist' in t for t in vs)
    print('  seeded rejector [dead manifest path]: %s'
          % ('REJECTED (as required)' if hit else 'NOT REJECTED — lint broken'))
    ok &= hit
    return ok


def run():
    try:
        d = rd.derive()
    except SystemExit as e:
        print('  DERIVE FAIL: %s' % e)
        return False
    text_now = rd.render(d)
    vs = check_bijection(d) + check_fresh(text_now) \
        + check_manifest(rq.MANIFEST)
    for t in vs[:40]:
        print('  VIOLATION ' + t)
    ok_seed = seeded_rejectors(d, text_now)
    nf = d['findings']
    ncrit = sum(1 for e in nf if e.get('path') == 'critical')
    nbc = sum(1 for b in d['bloc'] if b.get('path') == 'critical')
    ok = not vs and ok_seed
    print('  %-52s %s (%d steps; %d phases, %d gates, %d nodes, %d ledger, '
          '%d OPEN findings [%d critical], %d BLOCCATO [%d critical], %d '
          'open-class claims of %d, %d atlas mentions; %d overrides, %d '
          'OUT; manifest %d entries; %d violations)'
          % ('roadmap coverage lint (S-ROADMAP, derived not authored)',
             'PASS' if ok else 'FAIL', len(rd.STEPS), len(d['phases']),
             len(d['gates']), len(d['nodes']), len(d['ledger']), len(nf),
             ncrit, len(d['bloc']), nbc, len(d.get('claims_open', [])),
             len(d.get('claims', [])), len(d['atlas']),
             len(d['overrides']), len(d['outs']), len(rq.MANIFEST),
             len(vs)))
    return ok


if __name__ == '__main__':
    sys.exit(0 if run() else 1)
