# ESCALATION REFUTATION — DOC-2 (phaseD_meanswirl_formalization.md) r5
# escalation text, ROUND 2, LENS 1 (gas dynamics / physics, RH algebra,
# counterexamples)

Date: 2026-08-19 (S-FOUNDATIONS-C escalation window, until-dry round 2).
TARGET: the r5 REVISION ONLY — every passage carrying an "(r5)" marker
plus the passages those markers edit (header r5 block 98–135; (w1)
correction 1489–1503; two-of-three rider correction 1523–1539; H-CVX
connected-adiabat rewording 1574–1601; jump-set conclusion restatement
1602–1635; closure citation 1712–1717; ASSEMBLY rewrite 1730–1792 steps
(1)/(2)/(3); class/proof-state block 1802–1833; gamma status 1834–1841;
falsifier (d) 1876–1883; register row D.18 2135; G-f entry 2192–2194;
§6-quinquies ROUND 2 table 2410–2445) — and the leg-7 amendment A-1
carrier (D.2 H-CVX parenthetical 310–324, verified UNCHANGED at r5).
Adjudications of record consumed: `r2pass/VERDICT_r2pass.md` §2.1/§4(b)/
§4(c) (E-3 spec, A-1), full objection texts `r2pass/refute_r2batch_l0.md`
/ `refute_r2batch_l1.md` at legs 6–7, and BOTH round-1 escalation files
`r2pass/esc_doc2_r1_l0.md` (ESC-L0-1..4) and `r2pass/esc_doc2_r1_l1.md`
(ESC-1..4), read in full.

DEDUP DISCIPLINE: no dispositioned objection re-raised unless the
disposition itself fails (one finding below invokes exactly that clause,
with the ID cited and the failure derived). Every finding targets r5-NEW
text. All quotes verified verbatim against the r5 file (line reads).

MANDATE CHECK: for each of the eight round-1 objections answered by r5 I
verified (a) the round-1 objection text, (b) the landed r5 edit, (c) the
ROUND 2 ledger row. Results in §1; defects found in the landed text are
findings in §2, never silent.

==============================================================================
## §1 Discharge audit — do the r5 repairs discharge the eight round-1
##    objections (and does A-1 still stand)?

| Round-1 obj | r5 delivery | DISCHARGE VERDICT |
|---|---|---|
| ESC-L0-1 (BREAKS: r4 per-front dichotomy false on mixed front; "complete AS WRITTEN" attached) | Conclusion RESTATED in JUMP-SET form; mixed fronts explicitly admitted; the round-1 witness recorded in-statement as PASSING; "complete AS WRITTEN" retracted with the r4 sentence quoted | DISCHARGED AS TO ITS OWN WITNESS — the r4 dichotomy is gone and ESC-L0-1's tapering-shock instance passes the new form. BUT the replacement display mints a NEW false pointwise clause, broken by a boundary-sharpened variant of the same witness family (R2L1-1 below): the leg is again not "proved as written" |
| ESC-L0-2 (stale "made true" tag) | Tag RETRACTED by annotation inside the restated conclusion; mechanism (isentropic sheet at example-(α) grade) recorded; prior text quoted, never erased | DISCHARGED (§3 C-9; the recorded mechanism independently re-checked: [s]=0 sheet has zero s-atom, full-RH conservation atoms, zero a.c. part — K = 0 with a non-axisymmetric front, correct) |
| ESC-L0-3 + ESC-3 (two-of-three rider false/mis-witnessed) | Rider replaced: ALL SIX directions fail; witnesses re-attributed ((w1)/(w2) exact-side; (β) for the 2.5D side; φ-independent non-solution for the K = 0 side); defect recorded in-statement | DISCHARGED (§3 C-1/C-2: all six failure directions and all witness attributions independently re-derived and CHECK) |
| ESC-L0-4 (false universal (w1) + false "by definition") | (w1) re-scoped to the bounded-away class with K ≠ 0 derived from the a.c. leg under H-NC + H-WR; kernel-family collision recorded | DISCHARGED AS TO THE MECHANISM (§3 C-3: the a.c.-leg contrapositive on the bounded-away class is correct and the universal is now legitimate) — but the "e.g." EXEMPLAR adopted from the round-1 suggestion is NOT a member of the minted class (R2L1-3 below; disposition-failure clause invoked) |
| ESC-1 (assembly non-exhaustive on int{n_φ = 0} patches) | Assembly REWRITTEN in three steps; step (3) is row-free and stratification-free — no case split left to be non-exhaustive | DISCHARGED as to the exhaustiveness hole (§3 C-6/C-7). Step (1)'s supporting lemma has a new in-class failure mode (rides R2L1-1) |
| ESC-2 (a.e.→everywhere bridge unstated) | Bridge WRITTEN as step (1) | DISCHARGED AS SPECIFIED (the single-front bridge is what ESC-2 asked for) — but the written lemma over-claims: trace/jump continuity on a front FAILS at in-class front intersections and coincidence boundaries (rides R2L1-1; the a.e. grade it upgrades from is all that step (3) actually needs) |
| ESC-4 (arc H-CVX vacuously satisfiable on detached branch) | H-CVX reworded to CONNECTED-ADIABAT form; closure cites the supplied (not presupposed) segment; in-model exposure addressed | DISCHARGED as to vacuity (§3 C-4/C-5) — one citation gap in the in-model connectedness discharge (R2L1-2 below) |
| A-1 (leg 7, D.2 parenthetical) | UNCHANGED at r5 (verified: lines 310–324 still carry the r4 A-1 wording verbatim, no r5 marker) | STANDS — the two standing confirmations (r1_l0 B-9, r1_l1 §3.7) undisturbed. Cross-consistency check run: D.2's H-CVX keeps the arc form while D.18 moves to connected-adiabat — the divergence is DECLARED in D.18's hypothesis line ("unlike D.2's use (conditioning a monotonicity claim) this hypothesis must EXCLUDE a state"), which is exactly ESC-4's own scoping; not a defect |

Label discipline verified: both iff clauses still SCHEMA per
J-r2p-2/J-r2p-3 at all four sites (hypothesis/class block, register row
2135, G-f entry, ROUND 2 ledger); no self-upgrade; layer/gate caveat
carried forward. ROUND 2 ledger rows match the round-1 objection texts
1:1. The interrupted-slot RECONCILIATION note (header 124–135, ledger
2415–2425) was audited against the body: every claim the header makes is
delivered in the completed text; null=failure accounting honest.

==============================================================================
## §2 FINDINGS (3: 1 BREAKS-THE-LEG, 2 AMENDMENT)

------------------------------------------------------------------------------
**R2L1-1 — BREAKS-THE-LEG. The r5 jump-set conclusion's pointwise clause
("every front's JUMP SET is contained in int{n_φ = 0}") and its printed
"equivalently" to ∂_φV = 0 are FALSE on an in-class witness — a
boundary-sharpened variant of the document's own mixed front — and the
assembly step (1) lemma that feeds them ("one-sided traces of a
piecewise-C¹ field are CONTINUOUS on each front, so the jump [V] is
continuous there") is false for in-class multi-front fields; the r5
proof-state certification "proved as written" is thereby refuted for the
third consecutive round.**

Verbatim quotes (the attacked r5 passages):

Conclusion display (1623–1632):
> "The conclusion of record:
>   ∂_φ V = 0 AS A DISTRIBUTION on D × S¹_φ,
> equivalently: all fields φ-independent off fronts; every front's
> JUMP SET is contained in int{n_φ = 0} (front-relative interior — ...);
> and V coincides a.e. with a piecewise-C¹ MERIDIONAL field Ṽ(x, r), ..."

Assembly step (1) (1744–1753):
> "One-sided traces of a piecewise-C¹ field are CONTINUOUS on each
> front, so the jump [V] is continuous there; {g ≠ 0} ∩ {n_φ ≠ 0} is
> dense in the relatively open set {n_φ ≠ 0} (n_φ continuous on a C¹
> front), hence [V] ≡ 0 on {n_φ ≠ 0} and, by continuity, on its
> closure. Every front's jump set is therefore contained in
> int{n_φ = 0}."

Certification (1821–1823):
> "the second iff, in its r5 JUMP-SET form, is proved as written under
> H-NC + H-WR (+ connected-adiabat H-CVX on the n_m = 0 strata)"

WITNESS (coincidence-boundary mixed front; gas-dynamically ordinary).
Ṽ = an axisymmetric, wave-steady exact Euler solution carrying one
normal shock disc Σ = {x = 0} spanning the full annulus (no interior
tip, so no tapering is needed anywhere: the jump [Ṽ] = V₊ − V₋ ≠ 0 on
ALL of Σ), with swirl chosen so w_rel± ≠ 0 a.e. on Σ and both loci of
H-NC/H-WR have empty interior. V := Ṽ. Declared fronts (all C¹,
wave-steady, finitely many, in-class per §0 — judge act (v) of record
found no exclusion, and the r5 text itself admits jump-free and MIXED
declared fronts of record, 1633–1635): F = {x = k(r, φ)} over an
annular band, with k ≡ 0 on a closed parameter region P (so F coincides
with Σ exactly on P) and k > 0 with ∂_φk ≠ 0 a.e. immediately outside P
(C¹ contact: k, ∇k → 0 at ∂P; e.g. k = dist((r,φ), P)²·(2 + sin φ));
and C2' = closure(Σ ∖ P) carrying the rest of the shock. Then:
- V solves the exact 3-D wave-frame system distributionally (standard
  annular-duct normal shock; axisymmetric and lab-steady ⟹ wave-steady).
- K = 0 as a distribution: a.c. part zero (V axisymmetric); atoms: on
  C2', n_φ = 0; on F over P, n_φ = 0; on F off P, [V] = 0. LHS of the
  iff TRUE; ∂_φV = 0 TRUE; essential jump set = Σ, rotation-invariant —
  the theorem's CORE holds on the witness.
- BUT take q ∈ ∂P. Along F's normal line at q the one-sided limits
  exist and equal V₋(q) (from x < 0) and V₊(q) (from x > k), so F
  carries the FULL shock jump at q; equally, under the per-adjacent-
  piece-pair reading, the pair (upstream piece, outer downstream piece)
  adjoins across F on all of P with jump V₊ − V₋ ≠ 0 continuous up to
  ∂P. And q ∉ int{n_φ = 0}: n_φ(q) = 0 (by continuity from P) but
  {n_φ ≠ 0} accumulates at q (immediate helical departure). So F's jump
  set contains the whole curve ∂P, which is NOT contained in
  int{n_φ = 0}: the printed clause is FALSE, and with it the printed
  "equivalently" (∂_φV = 0 holds, the conjunction fails).

READING FORK, prosecuted both ways (the document nowhere pins the
definition of a front's jump set — itself part of the defect): (READING
A, normal-line or per-pair traces — the reading under which the r4
witness of ESC-L0-1 was adjudicated, since there too the jump was read
off a declared front): the display is a false mathematical statement on
the witness, exactly the severity class this pass prosecuted at L0-3 and
ESC-L0-1 ("the display of record is a false mathematical statement:
BREAKS", VERDICT_r2pass §2.1, even when repair is a one-line
restatement). (READING B, strict single-valued trace functions): at q
the trace functions have no limit, so q escapes the "jump set" — but
then step (1)'s lemma is refuted directly instead: on the witness the
below-F trace function equals V₋ on P and V₊ on the flap
(DISCONTINUOUS at ∂P), and [V]_F equals V₊ − V₋ on P and 0 on the flap
(DISCONTINUOUS at ∂P) — "one-sided traces ... are CONTINUOUS on each
front, so the jump [V] is continuous there" is false as printed, and
the closure upgrade "[V] ≡ 0 on {n_φ ≠ 0} and, by continuity, on its
closure" fails exactly at q ∈ closure{n_φ ≠ 0} (the essential jump
limit from the P side is V₊ − V₋ ≠ 0). On EITHER reading the
certification "proved as written" is refuted. Independently of the
exotic witness, the step-(1) lemma is false for ANY in-class field with
crossing fronts (in-scope physics: the RDE triple point — detonation,
oblique shock, slip line — meets along a curve; an axisymmetric Mach
reflection has [V]_C1 jumping at the crossing with C2, since the shock
strengths differ on the two sides): the lemma quantifies over
"piecewise-C¹ field ... each front" with no single-front or
away-from-intersections scoping.

Also note (over-attribution twin, folded in, not a separate finding):
under the normal-line reading the clause "jump set ⊆ {n_φ = 0}" would
even fail at a TRANSVERSAL crossing of a jump-free helical front with
an axisymmetric shock (the normal line crosses the shock at the
crossing point, so the shock's jump is read as the helical front's) —
so the repair below must also PIN the jump-set definition to
across-the-front adjacent piece pairs.

HONEST SCOPE: the theorem's core content survives the witness (∂_φV = 0,
V = Ṽ a.e., essential jump set rotation-invariant, all TRUE); step (3)
of the assembly needs only the a.e. grade of step (1) (the atom
n_φ[V]·dS dies as a measure once [V] = 0 a.e. on {n_φ ≠ 0}) and is
untouched. The break is in the printed pointwise clause, the printed
equivalence, and the printed lemma — all r5-new, all certified. Labels
already at SCHEMA per J-r2p-2/3, so no label motion is implied; but the
E-3 escalation cannot be adjudicated closed on this text, and the
ledger row ESC-1's "density dies pointwise" and the header's "all eight
objections are FIXED at full rigor" inherit the qualification.

NAMED REPAIR (transcription-grade): (i) define the front jump set via
across-the-front adjacent piece pairs; (ii) restate the clause in the
form that the proof actually delivers — "every front's jump set is
contained in {n_φ = 0}, and up to a front-null set in int{n_φ = 0};
the essential jump set is a rotation-invariant (meridional-curve × S¹)
set" (the last clause already printed and true); (iii) scope step (1)
to F ∖ (union of the other declared fronts and coincidence boundaries),
where the per-pair trace continuity IS true, and let step (3) run on
the a.e. grade it needs. CLASS: **BREAKS-THE-LEG** (false printed
display + false printed lemma + attached proved-as-written
certification, per this pass's own severity precedent).

NOVELTY/DEDUP: ESC-L0-1 attacked the r4 PER-FRONT dichotomy with a jump
strictly INSIDE the φ-invariant part (its witness passes the r5 form,
as the r5 text records); ESC-1 attacked case exhaustiveness; ESC-2
asked for the single-front a.e. bridge. None raised the coincidence-
boundary jump point, the multi-front failure of trace/jump continuity,
or the int-vs-closed {n_φ = 0} distinction — all three are properties
of r5-NEW text (grep of both r1 escalation files and both r2pass
lenses: no prior coverage).

------------------------------------------------------------------------------
**R2L1-2 — AMENDMENT. The in-model connectedness discharge attributes
no-detached-branch to the G_fund > 1 closed form alone, contradicting
the same passage's own accounting that connectedness/single-valuedness
needs Bethe's Γ_G > −2 BEYOND convexity; the one-line in-model fact
Γ_G = γ(T) − 1 > 0 is consumed unstated.**

Verbatim quotes (both anchors, r5): (hypothesis line, 1580–1582)
> "global single-valuedness of the Hugoniot needs subsidiary
> conditions — Bethe's Γ_G > −2 — beyond convexity"
and (the discharge, 1596–1600; twin at gamma status 1837–1841)
> "in the γ(T)-exact closure of record H-CVX is discharged
> unconditionally (closed form G_fund > 1, D.2, which ALSO makes the
> shock adiabat globally p-monotone and connected in range, so no
> detached branch exists where the model is defined ...)"

Attack. The two sentences cannot both stand as printed: if convexity
does not deliver global single-valuedness/connectedness (first
sentence, correct — Menikoff–Plohr's phase-transition regime is the
counterexample class), then "closed form G_fund > 1 ... ALSO makes the
shock adiabat ... connected in range" attributes to the closed form a
consequence the text just said convexity cannot carry. The in-model
CONCLUSION is true, but its missing ingredient is one line the document
never writes: for the §0 gas model (p = ρR_gT, h = h(T), c_p > 0), the
Grüneisen coefficient is Γ_G = v(∂p/∂e)_v = R_g/c_v = γ(T) − 1 > 0
> −2, so Bethe's subsidiary condition holds identically in-model and
the connected-adiabat hypothesis is discharged for EVERY RH trace pair.
CLASS: **AMENDMENT** — add the Γ_G = γ(T) − 1 > 0 line to the discharge
parenthetical (both anchors), or re-cite the connectedness to
"G_fund > 1 plus Γ_G > 0 (thermally perfect)" instead of the closed
form alone. No content change: the hypothesis rewording (ESC-4's
discharge) and the closure algebra are otherwise verified (§3 C-4/C-5).

NOVELTY: the connectedness-attribution sentence is r5-minted; ESC-4
(dispositioned FIXED) demanded the connected-adiabat form and the
in-model exposure note, not this citation's internal consistency.

------------------------------------------------------------------------------
**R2L1-3 — AMENDMENT. The corrected witness (w1)'s exemplar — "e.g. the
standing RDE wave-frame flow of record, [T-NSW]" — is not a member of
the class (w1) now mints: the standing flow is neither smooth nor
w_rel-bounded-away-from-c, by the document's own statements three
paragraphs below. (Disposition-failure clause invoked: the r5 text
adopted ESC-L0-4's suggested wording verbatim, and the suggestion's
exemplar parenthetical was itself defective.)**

Verbatim quote (1489–1494):
> "(w1) a smooth genuinely φ-dependent exact wave-frame solution with
> w_rel bounded away from 0 and c — e.g. the standing RDE wave-frame
> flow of record, [T-NSW] — has K ≠ 0 BY THE A.C. LEG of the second
> iff under H-NC + H-WR, which such a field satisfies"

Attack, from the document's own record. (a) SMOOTHNESS: the standing
RDE wave-frame flow of record is front-carrying (the detonation front
is the document's central singular object; §0/§5 class it as such) —
it is not "a smooth ... solution". (b) BOUNDED AWAY FROM c: the H-NC
discussion in the SAME hypothesis block (1544–1551) states that "the
in-scope CJ locus itself VIOLATES" the pointwise condition |w_rel| ≠ c
and that "the relative sonic locus IS the Chapman–Jouguet surface" of
that very flow — a flow containing its CJ surface in-scope has
inf|{w_rel} − c| = 0 and is not bounded away from c. So the exemplar
fails both class predicates, and the r4→r5 fix traded a false universal
for a non-member exemplar. The MECHANISM survives untouched (§3 C-3):
on the bounded-away class the universal is now true (the a.c.-leg
contrapositive is pointwise, so smoothness plus one point of
φ-dependence off the loci already forces K ≠ 0), and the witness role
is redundantly carried by (w2)/example (α) in the witness list
(1533–1535) — the damage is contained to the exemplar clause. CLASS:
**AMENDMENT** — either (i) restate the exemplar as the LOCAL fact the
flow actually instantiates ("any piecewise-smooth exact solution with
one smooth-region point where ∂_φV ≠ 0 and w_rel ∉ {0, ±c} has K ≠ 0 —
e.g. the standing flow on any compact smooth subregion of its marching
domain clear of the CJ surface, [T-NSW](a)"), or (ii) drop the exemplar
and let (w2) carry both exact-side directions, which it already does.

NOVELTY/DEDUP: ESC-L0-4 is dispositioned FIXED and its core (the false
universal + false "by definition") IS fixed — this finding attacks the
adequacy of the adopted repair text under the brief's disposition-
failure rule: the exemplar parenthetical originated in the round-1
suggestion and was never itself under attack until it became statement
text at r5. No prior ID touches the exemplar's class membership.

==============================================================================
## §3 CONFIRMED passages (strongest attack tried, each)

**C-1. Two-of-three rider correction (1523–1533) — CONFIRMED.**
Strongest attack: hunt for a direction that does NOT fail
unconditionally, or a witness mis-attribution. All six re-derived from
the operator identity: exact ⇏ 2.5D and exact ⇏ K = 0 (any (w1)-class
field or (α)); 2.5D ⇏ exact and 2.5D ⇏ K = 0 (example (β): sections
solve, 3-D RH violated, nonzero front atom); K = 0 ⇏ exact and
K = 0 ⇏ 2.5D (φ-independent smooth non-solution). "Any two imply the
third" is immediate from exact = reduced + K. The recorded r4-defect
quotation matches the r4 text of record. No defect.

**C-2. The φ-independent non-solution witness (1536–1539) —
CONFIRMED.** Strongest attack: is K ≡ 0 really identical for every
smooth φ-independent field? Yes: every div-form flux ∂_φF_φ,rel
vanishes, and the triangular recombination (invertible given ρ ≠ 0,
stated in the definition) forces every advective K row to zero;
smoothness kills atoms; the identity then gives exact-residual =
2.5D-residual, nonzero for a non-solution. CHECK.

**C-3. The (w1) MECHANISM (K ≠ 0 by the a.c. leg on the bounded-away
class) — CONFIRMED (modulo the R2L1-3 exemplar).** Strongest attack:
rebuild the kernel collisions. Bounded away from 0 kills the w_rel = 0
kernel (the r2 second kernel family needs an open co-rotation set);
bounded away from c kills the |w_rel| = c kernel; the a.c. leg is then
pointwise (K = 0 ⟹ ∂_φu = ∂_φv = ∂_φs = 0, then
(w_rel² − c²)∂_φρ = 0 ⟹ ∂_φρ = 0 ⟹ all ∂_φ = 0), so genuine
φ-dependence forces K ≠ 0 — the universal over the RESTRICTED class is
legitimate, exactly what ESC-L0-4 demanded. The "never by definition"
correction and the in-statement kernel-collision record are accurate.

**C-4. H-CVX connected-adiabat rewording (1574–1592) — CONFIRMED
(modulo R2L1-2).** Strongest attacks: (i) is a hypothesis on the
SOLUTION's traces (rather than on the EOS) legitimate here? Yes — H-NC
and H-WR are already solution-class hypotheses, and ESC-4's vacuity
analysis (adopted verbatim, correctly quoted) requires exactly this
form: the downstream trace ON the connected adiabat is what makes the
entropy-monotonicity step exclusionary rather than vacuous. (ii) Does
"the segment between the traces" presuppose uniqueness? On a connected,
single-valued (p-monotone) adiabat the segment is well-defined; the
existence/connectedness proviso carries M–P weak conditions + Γ_G > −2
— the right citations (their in-model verification is R2L1-2's line).
(iii) The D.2-vs-D.18 wording divergence is declared, not silent (§1,
A-1 row).

**C-5. The n_m = 0 closure re-citation (1712–1723) — CONFIRMED.**
Strongest attack: does strict entropy monotonicity really run on the
supplied segment? With the downstream trace on the connected adiabat
through the upstream trace and G_fund > 0 at every state of the segment
(Bethe–Weyl / Menikoff–Plohr package, the same one D.2 consumes,
confirmed twice at r2pass leg 7), s is strictly monotone in strength
through the zero-strength point (third-order contact [s] ~ (Δp)³ does
not break strictness), so [s] = 0 pins Δ = 0 on either branch;
[ρ] = [w_rel] = [p] = 0 then closes [w] (r continuous) and [h0]
(energy row). "The segment's existence is now supplied, not
presupposed" is exactly the ESC-4 discharge. The RH algebra of the case
was re-verified at round 1 (my §3.2) and is unchanged at r5.

**C-6. Assembly step (2), flow-invariance, "Sard-free" (1754–1759) —
CONFIRMED.** Strongest attack tried: the ODE-uniqueness/Osgood trap —
"e_φ tangent to a C¹ surface on a patch" does not, for a general
vector field, force orbit invariance without Lipschitz control of the
defining function. Killed by the graph argument: n_φ = 0 on an open
patch means the meridional normal components are nonzero, so the patch
is a C¹ graph x = a(r, φ) (or r = a(x, φ)) with n_φ ∝ ∂_φa; n_φ ≡ 0 on
the patch gives ∂_φa ≡ 0 on an open parameter set, i.e. a = a(r):
locally rotation-invariant, every point on a φ-arc inside the front.
No transversality, no Sard, no genericity — the printed claim is exact.

**C-7. Assembly step (3), distributional-∂_φ closure (1760–1772) —
CONFIRMED (and robust to R2L1-1's downgrade of step (1)).** Strongest
attacks: (i) the decomposition (1/r)∂_φV = {(1/r)∂_φV} + n_φ[V]·atom is
the standard piecewise-C¹ identity read along e_φ — CHECK; (ii)
normalization-independence: the atom's density carries the pointwise
factor n_φ[V] under ANY surface-measure convention, so the L0-5 G-f
deferral is genuinely not consumed — CHECK; (iii) does the closure
survive with only the a.e. grade of step (1)? YES — [V] = 0 a.e. on
{n_φ ≠ 0} already kills the atom as a measure ({n_φ = 0} contributes
the factor n_φ = 0 pointwise), and "a distribution with vanishing
φ-derivative on compact S¹ fibers is φ-independent" is the standard
fiber-average argument. This is why R2L1-1 breaks the printed display
and lemma but NOT the theorem's core: the repair is a restatement, not
new mathematics.

**C-8. The ⟸ re-read against the jump-set form (1773–1776) —
CONFIRMED.** Given the conjunction (jump set inside int{n_φ = 0}),
each atom n_φ[F_φ,rel] dies pointwise and the a.c. rows die by
∂_φV = 0. Trivial and correctly re-read. (R2L1-1 concerns ⟹ /
the equivalence, not this direction.)

**C-9. ESC-L0-2 retraction landing (1616–1623) — CONFIRMED.** The tag
is retracted by annotation at the display it certified, the
EOS-general falsity mechanism is recorded at the right construction
grade (checked: the isentropic sheet has m[s] = 0, so the K_s atom
vanishes with all conservation atoms — K = 0 with a genuinely
non-axisymmetric front), and the per-front falsity is cross-referenced
to the restatement. Prior text preserved in quotation. Annotate-never-
erase discipline satisfied.

**C-10. Falsifier (d) + G-f entry + register row + ROUND 2 ledger
(1876–1883, 2192–2194, 2135, 2410–2445) — CONFIRMED as bookkeeping
(with the two riders named in R2L1-1 inheriting its qualification: the
ledger ESC-1 row's "density dies pointwise" and the header's "FIXED at
full rigor").** Strongest attack: hunt a self-upgrade, a gate leak, or
a ledger row that mis-states its objection. None found: the mixed-front
instance (d) is a well-posed one-instance rejector (the ESC-L0-1
witness must PASS K = 0 and the r5 form and REFUTE the r4 dichotomy —
verified consistent: its jump set is strictly inside the φ-invariant
part, hence inside int{n_φ = 0}); the register row and G-f entry carry
the r5 state accurately; SCHEMA holds everywhere; the interrupted-slot
reconciliation is internally consistent and honestly declared.

**C-11. A-1 / D.2 parenthetical (310–324) — CONFIRMED STANDING.**
Verified unchanged at r5 (no r5 marker; wording = the judge's A-1
verbatim). Strongest attack: whether the r5 connected-adiabat rewording
in D.18 silently obligated D.2's arc form to change too — no: D.2's use
conditions a monotonicity claim (vacuity there is not failure), which
is ESC-4's own recorded scoping, now also quoted inside D.18's
hypothesis line. No re-open.

**C-12. Proof-state sentence structure (1812–1833) — CONFIRMED as
retraction mechanics; REFUTED as certification (that half is R2L1-1).**
The r4 "complete AS WRITTEN" sentence is quoted and retracted per the
annotate-never-erase discipline; the honest pricing sentence ("r5 is
the SECOND consecutive round in which the assembly step needed repair")
is accurate — and, per R2L1-1, now extends to a third.

==============================================================================
## §4 Summary

| ID | Target (r5 passage) | Class |
|---|---|---|
| R2L1-1 | jump-set display clause "every front's JUMP SET ⊆ int{n_φ = 0}" + printed "equivalently" + step (1) trace/jump-continuity lemma + "proved as written" certification | **BREAKS-THE-LEG** |
| R2L1-2 | in-model connectedness discharge cites G_fund > 1 alone against the passage's own Γ_G > −2 accounting; Γ_G = γ(T) − 1 > 0 consumed unstated (two anchors: 1596–1600, 1837–1841) | AMENDMENT |
| R2L1-3 | (w1) exemplar "the standing RDE wave-frame flow of record" is neither smooth nor bounded away from c, by the document's own CJ-locus statements; disposition-failure clause on the adopted ESC-L0-4 wording | AMENDMENT |

BREAKS-THE-LEG: 1. Total findings: 3. Everything else examined:
CONFIRMED with strongest attack recorded (§3 C-1..C-12). Discharge
audit: seven of eight round-1 objections DISCHARGED clean or as
specified; ESC-L0-1's replacement display mints a new false clause
(R2L1-1) — the E-3 escalation is NOT yet closable on the r5 text;
A-1 stands. Consistent with (and a reason for) the SCHEMA holding
labels: no label motion implied, the until-dry loop is not dry.

==============================================================================
## §5 Self-falsifiers for THIS refutation

- R2L1-1 dies if: (i) §0's front declaration is shown to exclude
  coincidence-boundary configurations (a declared front coinciding with
  the essential jump set on a patch and departing helically with C¹
  contact) — my read and judge act (v) found no such exclusion, and the
  r5 text itself admits mixed declared fronts; or (ii) a definition of
  "front jump set" is located in the document under which ∂P escapes
  the jump set AND step (1)'s lemma is literally true — note the two
  needs pull in opposite directions (READING B saves the display only
  by killing the lemma); or (iii) the witness is shown non-exact or
  K ≠ 0 (mechanically decidable: axisymmetric shock flow, atoms carry
  the factor n_φ[·] = 0 or [V] = 0 everywhere).
- R2L1-2 dies if a derivation is exhibited (in-document or at citation
  grade) that G_fund > 0 ALONE excludes detached Hugoniot branches —
  which would contradict the r5 hypothesis line's own Bethe sentence,
  itself adopted from ESC-4 and judge-consistent; or if the γ(T)
  discharge is shown to already cite Γ_G > 0 somewhere I missed (grep:
  "Γ_G" appears only in the two hypothesis-line/gamma-status anchors
  quoted, never with the in-model value).
- R2L1-3 dies if the standing RDE wave-frame flow of record is shown
  smooth (front-free) and with |w_rel| bounded away from c in-scope —
  both contradicted by the document's own §0/§5 front declarations and
  the H-NC block's CJ-locus sentences (1544–1551).
- The §3 confirmations die by exhibiting an error in any re-derivation
  (each reproducible: the six-direction witness table, the a.c.-leg
  contrapositive, the graph argument for flow-invariance, the
  piecewise-C¹ ∂_φ decomposition, the fiber-average argument, the
  Bethe–Weyl monotonicity closure, Γ_G = R_g/c_v = γ − 1).

END — machine summary: {objections: 3, breaks: 1,
file: validation/sfoundations_raws_2026-08-13/r2pass/esc_doc2_r2_l1.md}
