# ESCALATION REFUTATION — DOC-2 (phaseD_meanswirl_formalization.md),
# CONFIRMING ROUND (until-dry round 4 on the r7 text), LENS 0
# (hyperbolic-systems / functional-analytic rigor)

Date: 2026-08-19 (S-FOUNDATIONS-C escalation window, confirming round
mandated by `r2pass/VERDICT_escalation.md` §6 R-2).
TARGET: the REVISION r7 delta ONLY — every passage carrying an "(r7)" /
"r7" marker per the revision-log r7 block (183–227) and the
§6-quinquies ROUND 4 table (2953–3010). Marker census MEASURED this
window (grep for r7 tokens): 183–227 (log block); 1596 ((w1) exemplar
re-scope); 1806–1896 (CLASS PIN restatement (p1)–(p3), conclusion gloss,
grade-aligned structure clauses); 2020–2142 (step-(1) grade separation
(1a)/(1b), the WRITTEN (u1), density re-justification, INSENSITIVITY
NOTE type clarification, step-(3) atom re-typing, step-(3)(i) grade
fidelity, (⟸) re-run); 2189–2231 (class-block certification rewrite +
counter at FOUR); 2562 (register-row ROUND 4 clause); 2621–2628 (G-f
mixed-front RE-BIND); 2940–2951 (r7 annotation to the ROUND 3 table);
2953–3010 (ROUND 4 disposition table + residue paragraph). NO r7 marker
below 227 and above 1596, none in D.2 (A-1 at line 407 verified
untouched — grep this window).

ADJUDICATION CONTEXT CONSUMED FIRST: `r2pass/VERDICT_escalation.md` §2
DOC-2 (r7 unadjudicated; last adjudicated round sustained F-1 +
R3L1-1; theorem core survived every round) and §6 R-2 (one two-lens
round owed on the r7 delta; **over-certification counter at FOUR: any
fifth over-grade = REPAIR finding**) + §6 R-4 (BINDING: every repair
clause must be restated against the row's own hypotheses, never
transplanted verbatim from a refutation file — a transplanted clause
that misfits its row is a finding).

DEDUP: all prior escalation files read (`esc_doc2_r1_l0/l1`,
`esc_doc2_r2_l0/l1`, `esc_doc2_r3_l0/l1`) plus the r2batch leg-6/7
objections and `VERDICT_r2pass.md` §2.1/§4. No dispositioned objection
is re-raised except under the disposition-failure clause, with the ID
cited (CR-1 below cites F-1's own named-repair wording). All quotes
verified verbatim against the r7 file (line reads this window).

==============================================================================
## §1 BINDING R-4 RULE CHECK (transplant audit of the six r7 repair
##    clauses against their rows' own hypotheses)

| r7 repair clause | Source spec | Restated or transplanted? | Verdict |
|---|---|---|---|
| CLASS PIN (p1)–(p3) (1830–1845) | F-1 named repair (A) | RESTATED — and corrected against R3L1-2: F-1's option-(A) phrase carried "properly embedded up to H¹-RECTIFIABLE edges"; the r7 (p2) deliberately weakens to NULL edge sets with "locally H¹-rectifiable edges suffice WHERE they occur — no rectifiability is claimed or needed in general", exactly because R3L1-2 proved rectifiability false-in-general and consumed by nothing. A transplant would have re-imported the defect; the restatement removed it | PASS |
| Structure-clause grades (1866–1889) | R3L1-1 named repair (i) | RESTATED — and STRICTLY WEAKER than the refuter's own suggested scope: R3L1-1(i) offered "φ-independent H²-a.e. on the patch AND AT EVERY POINT OF cl(patch ∖ N_F)"; the r7 display claims only "OFF N_F ... hence H²-a.e." and explicitly does NOT claim the per-pair limits at patch ∩ N_F points. Safe direction | PASS |
| (u1) written (2037–2047) | R3L1-4 named repair | RESTATED — the ε-argument written in the document's own words against §0's values-only grant ("values near q′ approach the extension at q as q′ → q along the front"); the row's need (trace continuity on F ∖ N_F) is what it is applied to | PASS |
| (w1) rider re-scope (1588–1595) | F-3 + R3L1-3 repair phrases | RESTATED — goes BEYOND both refuter phrasings in honesty: "front-freeness and the pumping intersection are stated HYPOTHESES of the instance, not derived" is r7's own addition; neither refuter's phrase declared the predicates hypotheses. Residual probe on the lifted "(nonempty by the pumping record)" recorded at C-11 — resolved grammatically, no finding | PASS |
| G-f mixed-front RE-BIND (2621–2628) | F-4 repair option 2 | RESTATED — the re-bind names "the r6/r7 containment ... of record", proves the coincidence via the falsifier-(d) note, and adds the executor instruction ("an executor transcribes the containment of record, never the retracted display") that F-4's one-parenthetical spec did not contain | PASS |
| (⟸) re-run clause list (2131–2142) | F-1 named repair (B), final sentence | TRANSPLANT-MISFIT — the phrase "the essential jump vanishes a.e. by (1)" was carried over as "by step (1)'s unconditional clause (1b)" WITHOUT restatement against the direction's own hypothesis set: clause (1b) is proved FROM K = 0, which in ⟸ is the GOAL, not a premise | **FINDING CR-1** |

One instance of the R-4 pattern found (the seventh declared instance of
a repair-spec clause seeding the next round's finding, per the judge's
own count of six-plus).

==============================================================================
## §2 FINDINGS (2: 0 BREAKS-THE-LEG, 0 REPAIR-NEEDED, 2 AMENDMENT)

------------------------------------------------------------------------------
**CR-1 — AMENDMENT. The r7 (⟸) re-read supports its N_F ∩ {n_φ ≠ 0}
clause by citing "step (1)'s unconditional clause (1b)" — a proposition
whose printed derivation consumes K = 0 — inside the direction where
K = 0 is the CONCLUSION to be proved: invalid as a citation (the
hypothesis sets do not match), while the clause's CONTENT is true and
available one line away from the direction's own givens. The wording is
transplanted from F-1's named repair option (B) ("by (1)") without
restatement against the ⟸ hypotheses — the R-4 pattern, disposition-
failure clause invoked on F-1 to exactly this extent.**

Verbatim quote (2131–2142, r7-new):

> "(⟸, re-read against the jump-set form, stays trivial — RE-RUN AT
> THE a.e. GRADE, r7, F-1: the r6 re-read consumed 'N_F is front-null
> under the class pin' as a printed premise, which the r6 pin did not
> deliver; the direction never needed it: ∂_φ V = 0 kills every a.c. K
> row classically off fronts, and each front atom n_φ [F_φ,rel] dies AS
> A MEASURE because n_φ [F_φ,rel] = 0 H²-a.e. on each front — off the
> jump set [F_φ,rel] = 0 (equal pair limits + state-continuity of the
> fluxes); on the jump set minus N_F, n_φ = 0 (containment); and on
> N_F ∩ {n_φ ≠ 0} the ESSENTIAL jump vanishes a.e. by step (1)'s
> unconditional clause (1b) — no nullness premise consumed; under the
> r7 pin N_F is in any case front-null.)"

Derivation-level attack. The second iff's ⟸ direction has hypothesis
set {V solves the exact 3-D system distributionally} ∪ {the degenerate-
axisymmetric jump-set-form conclusion package} and goal K = 0. Clause
(1b) (2028–2033) is one of the two deliverables of assembly step (1),
whose printed derivation is the singular-leg case chains — and those
chains START from "K = 0 as a distribution then forces the meridional
RH TOO" (1929–1930) and, on the n_m = 0 stratum, from "What K = 0 ADDS
on this stratum is the s-row atom" (1967–1968). So (1b) is a
K = 0-CONSEQUENCE: "(1a)/(1b) UNCONDITIONALLY" means "without the class
pin", NOT "without K = 0" — and the ⟸ sentence trades on exactly that
ambiguity ("no nullness premise consumed" is true; the K = 0 premise it
cannot have is the problem). As printed, the third clause of the ⟸
justification is CIRCULAR: it derives K = 0 using a proposition proved
from K = 0.

The clause's CONTENT is nonetheless true from the ⟸ givens, by either
of two in-display routes, both one line: (i) the conclusion package's
own without-pin gloss (1859–1860): the containment holds "up to a
closed set carrying no ESSENTIAL-jump mass on {n_φ ≠ 0}" — the needed
statement, GIVEN, verbatim; equivalently under the pin, structure
clause (ii) plus front-nullness of N_F; or (ii) directly from the given
∂_φV = 0 through the step-(3) decomposition (2079–2081): 0 = (1/r)∂_φV
= {(1/r)∂_φV} + n_φ[V]·(front atom) with the a.c. part zero off fronts
(φ-independence, given), forcing n_φ · (essential [V]) = 0 H²-a.e. —
whence n_φ[F_φ,rel] = 0 essentially a.e. by state-continuity of the
fluxes. Route (ii) is the pin-free mechanism the residue paragraph's
"the ⟸ direction need[s] no pin at all — both now derived pin-free"
(2984–2985) implicitly relies on.

PROVENANCE (R-4): F-1's named repair option (B) ends "...on
N_F ∩ {n_φ ≠ 0} the essential jump vanishes a.e. by (1)" — the r7 text
adopted this final clause with the citation kept, although in the r7
home step (1) remained a K = 0-fed step (the refuter's phrase presumed
its own option-(B) restatement context). Transplanted-without-refit —
the seventh instance of the spec-seeding pattern R-4 binds against.

WHY NOT A FIFTH OVER-CERTIFICATION (adjudicated, not assumed): the
class-block sentence "is proved ... at the grades its clauses now
carry IN-LINE" (2192–2194) is a claim about CLAUSE GRADES, and the r7
grades are honest (verified at C-5/C-6/C-13 below); the counter of
record has counted STRENGTH claims (complete-as-written / proved-as-
written / at-exactly-the-strength), and the loop's own precedent for a
true conclusion with a mis-fit support citation is R3L1-4 = AMENDMENT,
which did NOT increment the counter. CR-1 is a citation-direction
defect with a correct in-display support one line away, not a printed
strength claim above the derivation. WHY NOT REPAIR: unlike F-1 (a
FALSE printed supporting claim consumed by four lines), nothing false
is printed — proposition (1b) is true; only its derivational
availability in this direction fails, and both correct routes are
already on the page.

NAMED REPAIR (one phrase, either option): replace "by step (1)'s
unconditional clause (1b)" with "by the conclusion's own without-pin
gloss (no essential-jump mass on the N_F residual)" — or with "by the
step-(3) decomposition applied to the GIVEN ∂_φV = 0 (the atom
n_φ·(essential [V]) must vanish a.e., forcing n_φ[F_φ,rel] = 0
essentially by state-continuity)". Class: **AMENDMENT**.

NOVELTY/DEDUP: the r7 (⟸) sentence is r7-minted; F-1(ii) attacked the
r6 nullness PREMISE, which IS repaired ("no nullness premise consumed"
is true); this finding invokes the disposition-failure clause on F-1
ONLY as to the adopted repair wording's residual citation — the same
ground on which F-3 prosecuted the adopted R2L1-3 wording at round 3.
No prior ID raises direction-hygiene of the (1b) citation.

------------------------------------------------------------------------------
**CR-2 — AMENDMENT. Referent collision on the token "(u1)": step (1)
prints "(u1), hereby WRITTEN" while the conclusion annotation in the
same revision prints "the a.e.→pointwise upgrade at N_F points (the
(u1) limit-matching plus gluing across N_F-separated arc components) is
NOT written and NOT claimed", and the register row compresses this to
"the a.e.→pointwise upgrade (u1)/(u2) NOT claimed" — a grep of "(u1)"
now returns both "hereby WRITTEN" and "is NOT written" for what
presents as the same object.**

Verbatim quotes (both r7-new). Conclusion annotation (1874–1877):

> "the a.e.→pointwise upgrade at N_F points (the (u1) limit-matching
> plus gluing across N_F-separated arc components) is NOT written and
> NOT claimed — the scoping option of R3L1-1's named repair is taken"

Step (1) (2035–2037):

> "each across-the-front adjacent piece pair persists locally and its
> one-sided traces ARE continuous: (u1), hereby WRITTEN (r7 CITATION
> CORRECTION, R3L1-4 ...)"

Register row (2562): "the a.e.→pointwise upgrade (u1)/(u2) NOT
claimed"; ROUND 4 table, R3L1-4 row: "line (u1) WRITTEN in step (1)
... (u1) now carries both the trace-continuity conclusion on F ∖ N_F
and the step-(3)(i) extension argument".

Attack. The two statements are RECONCILABLE — the annotation's subject
is the composite UPGRADE (the N_F-point application of the extension
line, plus the never-written gluing (u2)), while step (1) writes the
extension LINE itself and applies it only on F ∖ N_F — but the
annotation embeds the token "(u1)" inside the subject of "is NOT
written", and the register row labels the unclaimed route "(u1)/(u2)"
with no marker that (u1) alone IS written elsewhere in the same
revision. This is executor-facing cross-reference text of exactly the
species the loop prosecuted at F-4 (in-body twin annotated, spec entry
not) and R3L1-4 (support named that the cited source does not carry) —
exposure LOW (a reader of both passages in full can reconstruct the
referents; the ROUND 4 R3L1-4 row states the true state), which is why
this is an amendment and not a repair. NAMED REPAIR (one phrase, at
1874 and mirrored in the register row): "the a.e.→pointwise upgrade at
N_F points (the N_F-point application of the WRITTEN line (u1), plus
the unwritten gluing (u2)) is NOT claimed". Class: **AMENDMENT**.

NOVELTY/DEDUP: both passages are r7-minted (the (u1) label did not
exist in the document before r7); no prior ID can have raised it.

==============================================================================
## §3 CONFIRMED passages (every examined r7 delta passage I could not
##    break, each with the strongest attack tried)

**C-1. CLASS PIN restatement + (p1)–(p3) sufficiency derivation
(1806–1845) — CONFIRMED.** This is the round's proof-content
centerpiece and I attacked it hardest. (i) SELF-ACCUMULATION probe: a
front spiraling onto a 2-D patch of ITSELF would change piece structure
with no other front and no edge involved, escaping the printed
derivation ("can change only where the closure of the remaining front
set meets F or where F's own edge is approached") — DISSOLVED: an
embedded C¹ hypersurface is LOCALLY CLOSED (open in its closure), so
self-accumulation limit points lie in cl(F) ∖ F, i.e. in the (p2) edge
set; a fat one violates (p2). (ii) EDGE-CLOSURE probe: (p2) prices the
edge set null, but the derivation needs F ∩ cl(edge set), and closures
of null sets can be fat — DISSOLVED: local closedness makes cl(F) ∖ F
CLOSED, so F ∩ cl(edge set) = F ∩ edge set = ∅; the proper-embedding-
failure points ON F are themselves (p2)-priced. (iii) TANGENT-FRONT
probe: a front H approaching a φ-invariant patch to distance zero along
a curve C without touching it creates a two-pair/one-pair structure
change on C not covered by "lying on another declared front" — CAUGHT
by the derivation's own wording: C = F ∩ cl(H), i.e. "where the closure
of the remaining front set meets F", null by (p3); N_F's third
component picks C up and the nullness accounting closes. (iv)
REDUNDANCY probe: (p3) looks derivable from (p1)+(p2) when "edge set"
is read as all of cl(G) ∖ G — under the narrower reading (parameter-
boundary edges only) it is not, so (p3) closes a genuine reading gap;
stating a possibly-redundant sufficient clause is not a defect. (v) The
pin head "prices EXACTLY what the chain consumes — N_F IS FRONT-H²-NULL"
is F-1's option (A) taken honestly (the nullness IS the pin; (p1)–(p3)
a sufficient checkable form), and the phantom-front witness now
violates (p3) (and in fact (p2) as well — its cl(G) ∖ G is the fat
E-lift; the disposition row's "(p3)" is accurate, if not exhaustive).
The r6 pin is quoted in full with both defects mechanized
(annotate-never-erase verified).

**C-2. Rectifiability retraction inside the pin (1822–1828, 1835–1836)
— CONFIRMED; R3L1-2 DISCHARGED.** The (p2) parenthetical "locally
H¹-rectifiable edges suffice WHERE they occur — no rectifiability is
claimed or needed in general" is exactly the R3L1-2 repair, and it is
mathematically right in both directions: a locally H¹-rectifiable set
is H²-null (σ-finite H¹ ⟹ H² = 0), so the sufficiency clause is true;
and nothing downstream consumes rectifiability (re-checked: the
assembly, the gloss, step (1), step (3), the ⟸ re-read and falsifier
(e) consume H²-nullity only).

**C-3. Conclusion gloss + without-pin fallback (1855–1861) —
CONFIRMED.** "the nullness now holding BY the r7 class pin, which
prices it directly" — true by construction (C-1). Strongest attack on
the fallback gloss "up to a closed set carrying no ESSENTIAL-jump mass
on {n_φ ≠ 0}": is that proven pin-free? Yes — in the ⟹ direction it is
precisely clause (1b) (unconditional), and N_F is closed by definition;
the gloss claims nothing about per-pair jumps on N_F, which the
containment allows. The R2L1-1 witness re-run: null set exactly ∂P,
passes identically.

**C-4. Step-(1) grade separation (1a)/(1b) (2018–2033) — CONFIRMED.**
This is the F-1(iv) repair and I attacked its (1b) mechanism at
derivation level: "approximate limits ... exist H²-a.e. and are blind
to piece-structure changes (a pinching sliver has density 0)". Probe:
a cone-like contact (gap function k with k(q) = 0, ∇k(q) ≠ 0) gives a
sliver of POSITIVE density at q — does "density 0" fail fatly?
DISSOLVED at pen grade: for C¹ fronts the gap function k is C¹; on
{k = 0, ∇k = 0} differentiability gives k(x) = o(|x − q|), so the
sliver has 3-D density 0 at EVERY such point; {k = 0, ∇k ≠ 0} is
locally a C¹ curve in the front — H²-null. So approximate one-sided
limits exist H²-a.e. through the density-1 piece for ANY in-class
configuration (finitely many fronts ⟹ finitely many slivers), no pin
consumed — (1b)'s "UNCONDITIONALLY" is earned. (1a)'s "hence a.e. on
{n_φ ≠ 0} under the r7 pin" is a null-set absorption, exact. The
declared division of labor ("this clause is the ONLY one step (3)
consumes") verified against step (3): true.

**C-5. Grade-aligned structure clause (i) + step-(3)(i) derivation
(1878–1882, 2101–2120) — CONFIRMED.** Strongest attacks: (i) the
piece-level lemma "a continuous function equal a.e. to a φ-independent
one on a connected open set is φ-independent there" — re-proved
cleanly: F(p, p′) := V(p) − V(p′) on the open set
{(p, p′) : both in the piece, π(p) = π(p′)} is continuous and zero
a.e., hence ≡ 0 (connectedness not even needed). (ii) SAME-PAIR,
DIFFERENT-SECTOR probe: the same piece adjoining two same-fiber patch
points through different meridional approach sectors could give
different extension values — DISSOLVED off N_F: at q ∉ N_F no other
front's closure meets q (C-1(iii): tangent approaches land the contact
curve in N_F via the structure-change component), so the full one-sided
neighborhoods are single pieces locally and the (u1) extensions are
unrestricted one-sided limits; along a connected arc-component of
patch ∖ N_F the pair is locally constant hence constant, and the
extension of the φ-independent piece function is φ-independent along
it. (iii) NO-PAIR probe (my hardest): a front spiraling onto a fat
subset A of the patch with NO single piece adjoining at points of A —
those points would carry the clause with a vacuous derivation. UNDER
THE PIN this cannot escape: a no-pair point off N_F needs locally
constant no-pair structure, i.e. a fat accumulation set, violating
(p3); a null accumulation set puts its no-pair points in N_F via the
third component. Pin-free the clause is not asserted (fallback
sentence). The display's honest under-claim ("the per-pair limits AT
patch ∩ N_F points are not claimed") is the scoping option of
R3L1-1's named repair, strictly weaker than the refuter's own
suggestion — nothing to attack. F-2's grade wording ("everywhere off
N_F, hence H²-a.e. on the patch") is carried verbatim in substance.

**C-6. Grade-aligned structure clause (ii) (1882–1887, 2120–2129) —
CONFIRMED.** Strongest attack: is "rotation-invariant — unconditional"
really pin-free? Yes on the intrinsic reading: the essential jump set
is the non-approximate-continuity set of the a.e. class, and V = Ṽ∘π
a.e. makes the class rotation-invariant, so approximate limits
transform equivariantly — no front bookkeeping consumed. The product
structure is honestly scoped ("where it meets a front's int{n_φ = 0}
stratum ... up to the same front-null N_F geometry as the
containment"), and a circle meeting both int-strata and N_F is exactly
what the "up to" absorbs. The closing "at exactly the grades stated in
the conclusion (r7)" (2129) was probed as a possible echo of the
retracted certification formula: it is a clause-pair grade-match claim,
and the match was verified word-against-word (display 1878–1887 vs
derivation 2101–2129) — true, not an over-certification.

**C-7. The WRITTEN (u1) + citation correction (2034–2047) — CONFIRMED;
R3L1-4 DISCHARGED (modulo the CR-2 referent wording).** The ε-argument
is valid from §0's values-only grant: existence of the unrestricted
one-sided limit at EVERY front point forces the piece-side boundary
extension to be continuous where the pair persists — re-derived; no
C¹-up-to-the-boundary regularity is consumed anywhere in the r7 text
(grep for the retracted phrase: only inside the quoted r6 annotation).

**C-8. Density re-justification by closedness (2048–2054) —
CONFIRMED.** "the density conclusion never depended on the pin" is
exact: N_F closed makes {n_φ ≠ 0} ∖ N_F relatively open; an
H²-a.e.-full subset of a C¹ front is dense in every relatively open
subset (positive H² of relatively open sets); the containment chain
then runs by continuity WITHIN F ∖ N_F — re-derived, matching the
round-3 C-2 verification, now with the correct printed reason.

**C-9. INSENSITIVITY NOTE type clarification + step-(3) atom re-typing
(2058–2066, 2080–2089) — CONFIRMED.** Here the (1b) citation IS
legitimate: step (3) sits in the ⟹ direction where K = 0 is a
hypothesis, so consuming a K = 0-derived clause is well-founded (the
contrast with the ⟸ re-read is exactly CR-1's point). "the atom is an
H²-a.c. measure and sees only ESSENTIAL jumps" — correct: as a measure
identity the jump coefficient at H²-a.e. front point is the difference
of approximate limits (BV-trace grade), which exists a.e. by C-4; the
r6 "any H²-null exceptional set is invisible" nullness-assuming
parenthetical is quoted, never erased.

**C-10. (⟸) re-read, first two clauses + conclusion (2131–2142) —
CONFIRMED as a direction (its third-clause citation is CR-1).** "off
the jump set [F_φ,rel] = 0" — equal pair limits + state-continuity:
valid; the essential jump set ⊆ per-pair jump set (an essential jump
point has some adjoining pair with unequal limits — density-positive
pieces carry the approximate limits), so the three clauses jointly
cover {n_φ ≠ 0} at essential type. The direction is TRUE from its
givens by the one-line decomposition route recorded in CR-1; "no
nullness premise consumed" is accurate; the pin rider is harmless.

**C-11. (w1) exemplar re-scope (1588–1614) — CONFIRMED.** Strongest
attacks: (i) EXISTENCE — front-freeness and pumping-intersection are
now "stated HYPOTHESES of the instance, not derived": honest, and
strictly more than either refuter's repair phrase demanded; probed the
residual "(∂_φV ≢ 0 on the subdomain — nonempty by the pumping record
∂_φp ≠ 0 off fronts)" for a smuggled existence claim (is the pumping
point of record known to sit INSIDE the marching domain?): on the
natural grammatical attachment "nonempty" modifies the D.19 pumping
region {∂_φp ≠ 0 off fronts}, which IS nonempty of record — the
subdomain's meeting it stays hypothesis-side; no unproven universal
survives. (ii) "[T-NSW](a) then supplies |w_rel| bounded away from c
on the compact closure" — compact closure inside the open hyperbolic
region + continuity: valid (the round-3 C-6 mechanism, now with the
front-free qualifier making "smooth instance" true BY HYPOTHESIS).
(iii) The r6 rider is quoted in full with BOTH universals mechanized
and the three-generation history recorded — the annotation's content
checked against F-3/R3L1-3 line-by-line: faithful.

**C-12. G-f mixed-front RE-BIND (2621–2628) — CONFIRMED; F-4
DISCHARGED.** The pass-criterion of record is now the r6/r7 containment
(unchanged as a display from r6 to r7 — only the pin's pricing moved,
verified); the coincidence proof on the instance (jump set avoids N_F:
single connected front, no crossings/edge contact/structure change) was
re-checked and matches the in-body falsifier-(d) note; the executor
instruction removes the last transcription ambiguity. Annotate-never-
erase: the r5 wording survives in place.

**C-13. Class-block certification rewrite + counter at FOUR
(2186–2231) — CONFIRMED.** (i) The replacement sentence "at the grades
its clauses now carry IN-LINE" was attacked as a candidate FIFTH
over-certification via CR-1: adjudicated NOT an over-grade (grades are
honest and verified C-5/C-6; CR-1 is a citation defect, per the R3L1-4
precedent). (ii) Counter arithmetic re-done from the record: the two
round-3 lenses counted DIFFERENT triples both summing to three (l0:
r4 complete-as-written / r5 header / r5 proved-as-written; l1: r3 tag /
r4 / r5) — either way the r6 "at exactly the strength" is the FOURTH,
and the r7 text records FOUR: consistent. (iii) The assembly-repair
counter ("r7 the FOURTH" at 2227) is a separate counter and its
arithmetic checks (r5, r6, r7 repairs on r4's assembly = second, third,
fourth). (iv) Labels: both iff clauses at SCHEMA per J-r2p-2/J-r2p-3 at
all four sites (class block 2176–2177 and 2229–2231; register row
2562; G-f entry; revision log 223–224); E-3 left to the window judge;
layer/gate caveat carried verbatim. No self-upgrade anywhere in the r7
delta.

**C-14. ROUND 4 disposition table + r7 annotation to the ROUND 3 table
(2940–2976) — CONFIRMED as bookkeeping.** Row-against-file check for
all eight objections: each Item column matches its source objection
text 1:1 (both round-3 files re-read this window); each Disposition
row's mechanism was verified present in the body at the stated place
(F-1 → (p1)–(p3) + (1a)/(1b) + gloss + density + ⟸ + re-typing;
R3L1-1 → scoping option with (u1)/(u2) named-not-claimed; F-2 merged;
F-3/R3L1-3 merged rider; F-4 re-bind; R3L1-2 gloss retraction inside
the pin; R3L1-4 (u1) written). The annotation's discharge mirror
(R2L1-1/ESC2-L0-2/ESC2-L0-4/R2L1-2 discharged; ESC2-L0-1,
ESC2-L0-3/R2L1-3 partial) matches the two files' own §1 tables. The
"named repair option (A) taken AND the essential-type re-route of
option (B) written where step (3) consumes it" claim is accurate — and
the one clause where option (B)'s wording was carried into the ⟸
without refit is CR-1, which the table's own "(⟸) re-read re-run at
a.e. grade, no nullness premise" row does not misstate (the row claims
no-nullness, which is true; it does not claim citation hygiene).

**C-15. Residue paragraph (2978–3010) — CONFIRMED, with one rider.**
The two declared prices are real and correctly signed: (p2)/(p3) is a
GENUINELY STRONGER hypothesis than the r6 pairwise clause (verified:
the phantom witness satisfies r6-pin and violates r7-pin), and the
structure clauses are genuinely weakened with the downstream
non-consumption census re-checked (S.22 consumes the K identification;
the G-f instances consume K verdicts + containment — neither consumes
flat clauses or Ṽ-regularity). "the ⟸ direction ... now derived
pin-free" is TRUE of the direction's mathematics but inherits CR-1's
citation defect as printed. Counter move THREE → FOUR recorded; "No
new G-f instance was needed this round (the falsifier list is
unchanged; F-4 re-binds an existing item)" — verified by diffing the
falsifier block markers: no new instance token.

**C-16. Register-row ROUND 4 clause (2562) — CONFIRMED (modulo the
CR-2 compression).** Every enumerated delivery re-verified against the
body; "front-null BY THE r7 RESTATED PIN" correctly re-prices the
ROUND 3 clause's inherited defect in place; SCHEMA held in the row's
class column.

**C-17. Revision-log r7 block (183–227) — CONFIRMED.** Items (1)–(5)
each verified against the landed body text; the (p1)–(p3) summary
matches the pin verbatim in substance; "the (⟸) re-read is re-run at
the a.e. grade with no nullness premise" is true as stated (CR-1 lives
in the body's citation, and the log does not over-state it); A-1
re-confirmation claim consistent with both round-3 lenses' C-rows.

**C-18. Leg-7 / A-1 (D.2 parenthetical, line 407) — CONFIRMED, no
regression.** Grep this window: no r7 marker below the log block
touches D.2; the judge's A-1 wording ("genuinely nonlinear WITH the
convex (compressive-shock) orientation") stands verbatim at 407; the
r7 edits nearest to D.2's consumers (the H-CVX hypothesis line) are
r5/r6-era text outside this round's target. The D.2-arc vs
D.18-connected-adiabat divergence remains DECLARED and correctly
scoped.

==============================================================================
## §4 Summary

| ID | Target (r7 passage) | Class | One-line |
|----|---------------------|-------|----------|
| CR-1 | (⟸) re-read, third clause "by step (1)'s unconditional clause (1b)" (2131–2142) | AMENDMENT | (1b) is K = 0-fed; K = 0 is the ⟸ GOAL — circular as a citation; content true and available from the conclusion's own without-pin gloss or ∂_φV = 0 + the step-(3) decomposition; transplanted from F-1 option (B) without refit (R-4, seventh instance) |
| CR-2 | "(u1) ... is NOT written" (1874–1877) vs "(u1), hereby WRITTEN" (2037) + register-row "(u1)/(u2) NOT claimed" (2562) | AMENDMENT | referent collision between the composite upgrade and the written extension line; one disambiguating phrase |

BREAKS-THE-LEG: 0. REPAIR-NEEDED: 0. AMENDMENT: 2. Eighteen r7 delta
passages CONFIRMED with strongest attacks recorded, including the
round's two proof-content repairs (the (p1)–(p3) pin sufficiency
derivation and the (1a)/(1b) grade separation), both of which
withstood witness-construction attacks at pen grade. R-4 audit: five
of six repair clauses RESTATED compliantly (two of them corrected
their source refuters' own phrasing — the anti-transplant discipline
visibly operated); one transplant-misfit found (CR-1). The
over-certification counter stays at FOUR on this lens's adjudication:
no r7 sentence prints a strength above its written derivation — the
two findings are citation/cross-reference hygiene, not grade
inflation. DRYNESS STATEMENT: zero derivation-content defects remain
on this lens; for the second consecutive round every constructed
witness PASSES every conclusion clause of record, and for the FIRST
time no printed supporting claim is false — what separates the r7
text from dry is two one-phrase amendments.

==============================================================================
## §5 Self-falsifiers for THIS refutation

- CR-1 dies if: (i) clause (1b) is shown derivable IN-DOCUMENT without
  K = 0 (my read of step (1): the case chains it invokes start from
  "K = 0 ... forces the meridional RH" at 1929–1930 and "What K = 0
  ADDS" at 1967 — both K = 0-fed; no alternative derivation of (1b) is
  printed); or (ii) the ⟸ direction's given package is adjudicated to
  INCLUDE the step-(1) clauses as conclusion content (the pin fallback
  sentence's "(steps (1)/(3))" pointer could be read as incorporating
  them — under that reading the citation type-checks and the finding
  drops to a request for one clarifying pointer; the certification
  question stays closed either way since the content is true); or
  (iii) the loop's conventions are shown to count citation defects
  into the over-certification counter (then CR-1 escalates per §6 R-2
  and my adjudication paragraph is the part refuted, not the finding).
- CR-2 dies if the document's conventions are shown to distinguish
  "(u1)" (the line) from "the (u1) limit-matching" (the application)
  as established referents (my grep found the token minted at r7 with
  no such convention declared).
- The §3 confirmations die by exhibiting an error in any recorded
  re-derivation, each reproducible: the locally-closed-embedded-
  submanifold resolution of the self-accumulation and edge-closure
  probes (C-1); the H² nullity of {k = 0, ∇k ≠ 0} and k = o(dist) at
  ∇k = 0 (C-4); the F(p, p′) continuity lemma and the no-pair pin
  analysis (C-5); the intrinsic rotation-equivariance of approximate
  limits (C-6); the counter arithmetic from the two lens files (C-13);
  the row-against-file table checks (C-14); the A-1 grep (C-18). In
  particular, an in-class exact-solution witness violating any r7
  conclusion clause AT ITS PRINTED GRADE would simultaneously kill the
  corresponding confirmation and re-open the leg — my constructions
  (cone-contact sliver, spiral no-pair accumulation, tangent-front
  curve) all FAIL to violate the printed grades, and each failure
  mechanism is recorded above.

Confirming-round lens-0 totals: 2 objections (0 BREAKS / 0 REPAIR /
2 AMENDMENT), 18 passages CONFIRMED with strongest attacks recorded.
Nothing else in the r7 delta withstood less than the attacks listed.

END — machine summary: {breaks: 0, repairs: 0, amendments: 2,
file: validation/sfoundations_raws_2026-08-13/r2pass/esc_doc2_confirm_l0.md}
