# ESCALATION REFUTATION — DOC-2 (phaseD_meanswirl_formalization.md) r7
# text, CONFIRMING ROUND (until-dry round 4), LENS 1 (gas dynamics /
# physics, RH algebra, counterexamples)

Date: 2026-08-19 (S-FOUNDATIONS-C escalation window, confirming round on
the r7 revision — the round VERDICT_escalation §6 R-2 names as owed).
TARGET: the REVISION r7 delta ONLY — every passage carrying an "(r7)" /
"r7" marker per the revision-log r7 block (lines 183–227) and the
§6-quinquies ROUND 4 table (2953–3010). Marker sweep executed this
window (grep "r7", all non-header hits): 1596 ((w1) exemplar re-scope);
1806–1847 (CLASS PIN restatement (p1)–(p3) + sufficiency derivation);
1855–1862 (conclusion "i.e." gloss re-derived from the r7 pin +
without-pin honest gloss); 1862–1889 (grade-aligned structure clauses
(i)/(ii) + the NOT-claimed (u1)/(u2) upgrade annotation); 1896 (proof
header parenthetical); 2020–2033 (step-(1) GRADE SEPARATION into
(1a)/(1b)); 2034–2047 ((u1) WRITTEN, citation correction); 2048–2054
(density parenthetical re-justified by closedness); 2058–2066
(INSENSITIVITY NOTE r7 type clarification); 2084–2089 (step-(3) atom
parenthetical re-typed to essential jumps); 2101–2129 (step-(3)(i)/(ii)
transcriptions at r7 grades); 2131–2142 ((⟸) re-read RE-RUN at a.e.
grade); 2186–2231 (class/proof-state block: r7 grades-in-line
certification + over-certification counter at FOUR); 2562 (register row
ROUND 4 clause); 2621–2628 (G-f mixed-front RE-BIND); 2940–2951 (r7
annotation on the ROUND 3 table); 2953–3010 (ROUND 4 disposition table +
residue paragraph). Leg-7 / A-1 scope: grep-verified NO r7 marker below
the header block touches D.2 (nearest body marker: 1596); the A-1
landing ("i.e. genuinely nonlinear WITH the convex (compressive-shock)
orientation", ~404–405) verified verbatim on disk, no regression (C-15).

Adjudications of record consumed FIRST, per brief:
`r2pass/VERDICT_escalation.md` §2 DOC-2 (r7 unadjudicated; core survived
every round; two round-3 findings proof-content) and §6 R-2 (one
two-lens round owed on the r7 delta; **over-certification counter at
FOUR — any fifth over-grade = REPAIR finding**) + §6 R-4 (binding rule:
every repair clause restated against the row's own hypotheses, never
transplanted verbatim from a refutation file — six-plus prior
instances). Both round-3 files (`esc_doc2_r3_l0.md` F-1..F-4,
`esc_doc2_r3_l1.md` R3L1-1..4) read in full; round-1/round-2 escalation
files and the r2batch leg-6/7 objections consulted for dedup.

DEDUP DISCIPLINE: no dispositioned objection re-raised unless the
disposition itself fails (none is claimed to fail below — all eight
ROUND 4 dispositions verified sound as dispositions; my three findings
target r7-MINTED text with zero prior coverage, grep declared per
finding). All quotes verified verbatim against the r7 file (line reads
this window).

==============================================================================
## §1 BINDING R-4 RULE CHECK — restated-vs-transplanted audit of all
##    eight r7 repair clauses (VERDICT_escalation §6 R-4)

| r7 repair clause | Provenance vs the refutation files | VERDICT |
|---|---|---|
| CLASS PIN (p1)–(p3) (1830–1845) | F-1's named repair option (A) read "properly embedded up to H¹-rectifiable edges, and no declared front accumulates on another outside an H²-null set" — transplanting it VERBATIM would have re-imported the rectifiability gloss R3L1-2 killed. The r7 text RESTATED it: (p2) demands only an H²-null edge set with rectifiability demoted to "suffice WHERE they occur — no rectifiability is claimed or needed in general", and a sufficiency DERIVATION (1838–1845) is written against the row's own N_F definition | RESTATED, correctly merged with R3L1-2 — a positive R-4 instance |
| Step-(1) split (1a)/(1b) (2020–2033) | F-1 option (B)'s essential-type clause was written FOR the measure-level atom argument ("no exceptional set needed, as the INSENSITIVITY NOTE already says"). The r7 (1b) restates it as a standalone clause with its OWN fresh justification — and that justification runs HOT of the source (finding R4L1-2 below: an approximate-limit existence universal the source clause never carried and no consumer needs) | RESTATED WITH A HOT JUSTIFICATION — the R-4 pattern's inverse (the transplant would have been safer); prosecuted at R4L1-2 |
| Structure-clause grade alignment (1862–1889, 2101–2129) | R3L1-1's scoping option adopted with the F-2 mechanism written into step (3)(i) against the row's own step-(2) product structure | RESTATED — but the label "(u1)" was carried over from R3L1-1's text into TWO different roles (finding R4L1-1 below): the transplanted NAME misfits the row |
| (u1) written (2034–2047) | R3L1-4's named repair phrase ("existence of unrestricted one-sided limits ... whose piece-side boundary extension is continuous") restated with the ε-argument named and §0 untouched | RESTATED against §0's own values-only grant — clean |
| (w1) re-scope (1588–1614) | R3L1-3's own repair phrase adopted per the ROUND 4 row — NOT verbatim: "clear of the CJ surface" retained, ∂_φp strengthened to ∂_φV for the membership predicate, and the joint-satisfiability exposure priced by a NEW hedge ("front-freeness and the pumping intersection are stated HYPOTHESES of the instance, not derived") the refuter's phrase did not carry | RESTATED with an added honest price — clean (attack tried and dissolved, C-10) |
| G-f mixed-front re-bind (2621–2628) | F-4's repair option 2 restated with the falsifier-(d) coincidence mechanism transcribed and the executor instruction ("transcribes the containment of record, never the retracted display") added | RESTATED against the instance's own witness geometry — clean |
| Density parenthetical (2048–2054) | F-1(iii)'s observation restated as a re-justification by CLOSEDNESS with the defect recorded | RESTATED — clean |
| (⟸) re-read re-run (2131–2142) | F-1(ii)'s named rewrite ("rewrite the (⟸) re-read through the a.e. grade") — the r7 text transplants the three-case shape of F-1's suggested rewrite but sources case 3 from "step (1)'s unconditional clause (1b)", a FORWARD step, where F-1's own rewrite said "the essential jump vanishes a.e. by (1)" in a context where (1) was available | TRANSPLANTED SHAPE, MIS-SOURCED CASE — the direction-of-derivation misfit is finding R4L1-3 below |

==============================================================================
## §2 FINDINGS (3: 0 BREAKS-THE-LEG, 0 REPAIR-NEEDED, 3 AMENDMENT)

------------------------------------------------------------------------------
**R4L1-1 — AMENDMENT. The label "(u1)" is OVERLOADED by the r7 edits
into two contradictory roles: the conclusion annotation prints "(u1)
... is NOT written and NOT claimed" while step (1) prints "(u1),
hereby WRITTEN" — and the ROUND 4 table repeats the collision in
adjacent rows. An executor or successor refuter grepping "(u1)" finds
the document asserting both that it wrote (u1) and that it did not.**

Verbatim quotes. Conclusion annotation (1874–1877):

> "the a.e.→pointwise upgrade at N_F points (the (u1) limit-matching
> plus gluing across N_F-separated arc components) is NOT written and
> NOT claimed — the scoping option of R3L1-1's named repair is taken"

Step (1) (2037):

> "ARE continuous: (u1), hereby WRITTEN (r7 CITATION CORRECTION,
> R3L1-4 ...)"

ROUND 4 table, adjacent rows: R3L1-1 row — "the (u1)/(u2) UPGRADE
route is named and NOT claimed"; R3L1-4 row — "line (u1) WRITTEN in
step (1) ... (u1) now carries both the trace-continuity conclusion on
F ∖ N_F and the step-(3)(i) extension argument".

Derivation-level attack. R3L1-1's original (u1) bundled TWO contents:
(a) the boundary-extension continuity lemma (a C¹ piece with
unrestricted one-sided limits has a continuous extension to its closed
piece), and (b) its application AT N_F points ("the trace at an N_F
point is the limit of nearby patch ∖ N_F trace values"). The r7 text
correctly wrote (a) — it is consumed by step (1)'s trace continuity on
F ∖ N_F and by step (3)(i)'s extension argument — and correctly
DECLINED (b) (the scoping option). But it kept the single label "(u1)"
for both halves: at 2037 "(u1)" = content (a), WRITTEN; at 1874–1876
"(u1) limit-matching" = content (b), NOT written. This is an R-4-rule
instance in the exact sense the verdict binds: the NAME was
transplanted from the refutation file into the row without restating
which half of the source clause it now denotes, and the transplanted
name misfits — the document contradicts itself at the label level
(substantively both sentences are true of their respective contents;
verified: nothing at an N_F point is claimed anywhere, and the written
extension lemma is applied only off N_F — C-6). Exposure: an executor
building the G-f checks, or the E-3 judge, greps "(u1)" and must
resolve "NOT written" against "hereby WRITTEN" by reading intent — the
precise defect class (executor-facing name ambiguity) the loop
prosecuted at F-4 and L1-5. REPAIR (one edit): rename the unclaimed
half — e.g. "(the (u1′) limit-matching AT N_F points plus the (u2)
gluing across N_F-separated arc components) is NOT written and NOT
claimed — (u1) itself, the extension lemma, IS written and consumed
only off N_F" — and mirror the rename in the ROUND 4 R3L1-1 row.
Class: **AMENDMENT** (no conclusion motion; both statements true of
their intended referents; label collision only).

NOVELTY/DEDUP: both quoted passages are r7-minted; grep of all
esc_doc2 files — "(u1)" appears only in the round-3 files as the
SOURCE clause; no prior ID raises a label collision (the collision
could not exist before r7 wrote one half).

------------------------------------------------------------------------------
**R4L1-2 — AMENDMENT. Clause (1b)'s r7-written justification prints an
UNDERIVED measure-theoretic universal — "the essential jump is read
through approximate limits, which exist H²-a.e." — that no consumer of
(1b) needs and nothing written supports beyond a one-line sliver
heuristic: the clause's own content (the essential jump set ∩
{n_φ ≠ 0} is H²-null) quantifies BY DEFINITION over points where
approximate limits exist, and step (3)'s atom argument is measure-level
(K = 0 kills the H²-a.c. singular measure directly). The same
transplanted-clause-runs-hot species as F-1's own history: the source
clause (F-1 option (B)) was safe because its consumer was the measure
argument; restated as a standalone clause, it acquired a pointwise
existence claim.**

Verbatim quote (2028–2033):

> "(1b) UNCONDITIONALLY (no pin), [V] = 0 at ESSENTIAL-jump type
> a.e. on {n_φ ≠ 0}: the essential jump is read through
> approximate limits, which exist H²-a.e. and are blind to
> piece-structure changes (a pinching sliver has density 0), so
> the same case chains run at essential type with no exceptional
> set — and this clause is the ONLY one step (3) consumes."

Derivation-level attack. (a) The existence universal is UNPROVEN as
written for the unconditioned (no-pin) class. The only written support
is the sliver parenthetical. I re-derived the sliver claim and it is
CORRECT where it applies — at H²-a.e. (density) point q of an
accumulation set E, a sliver {0 < z < k} under a front touching down
on E has 3-D density 0 at q, with NO Lipschitz hypothesis on k needed
(split the shadow of B_ρ: the E-part contributes 0 since k = 0 there;
the non-E part has plane-density o(ρ²) at a density point of E and
contributes ≤ ρ · o(ρ²) = o(ρ³)) — but that computation covers ONE
accumulation geometry, and the universal quantifies over every
in-class no-pin configuration, including nested multi-front
accumulations where sheets of positive local density alternate. §0
grants unrestricted one-sided limits PER PAIR at every front point;
where the approach side splinters into infinitely many pairs whose
densities do not resolve (countable additivity fails for densities),
nothing written delivers an approximate one-sided limit. I could NOT
construct an in-class failure: every jump-carrying accumulation
attempt dies because near a clean accumulation stratum the
accumulating front's own per-pair jumps vanish EVERYWHERE by
(1a)+(u1)-continuity on its N-free part (the oscillation source is
self-extinguishing), and the regress into nested fat N-sets could not
be closed into an exact solution — recorded in the self-falsifier.
(b) The universal is UNCONSUMED. (i) By (1b)'s own content: "[V] = 0
at essential-jump type a.e. on {n_φ ≠ 0}" says the ESSENTIAL JUMP SET
(where two-sided approximate limits exist and DIFFER — Federer type)
meets {n_φ ≠ 0} in an H²-null set; points without approximate limits
are outside the essential jump set by definition, so the clause is
provable by running the case chains only at essential-jump points
(where limits exist by definition, g ≠ 0 a.e., and the K = 0 atom
vanishing gives the essential flux RH a.e.) — no existence universal
enters. (ii) By step (3): the atom is an H²-a.c. measure killed AS A
MEASURE by K = 0; the insensitivity note itself says the closure
consumes "ONLY the a.e. grade at ESSENTIAL-jump type ... with no
exceptional set and no pin at all". (iii) By the (⟸) re-read: same
measure grade. So the sentence is a supporting claim printed as fact,
consumed by nothing — the exact L0-5/R3L1-2 precedent class
(unconsumed underived gloss), in fresh r7 text. IMPORTANT FOR THE R-2
COUNTER: this does NOT make the r7 certification a fifth over-grade —
the CLAUSE's stated grade (essential-type, a.e., unconditional) IS
delivered by the written case chains read at essential-jump points;
only the justification's route over-reaches (§4 below). REPAIR (one
edit): "the essential jump is read through approximate limits — which
exist BY DEFINITION at every essential-jump point, and at H²-a.e.
point of each witness geometry of record (a pinching sliver has
density 0 at density points of its accumulation set) — so the same
case chains run at essential type with no exceptional set". Class:
**AMENDMENT**.

NOVELTY/DEDUP: clauses (1a)/(1b) and this justification are r7-minted
(the r6 step (1) carried the flat per-pair claim F-1(iv) killed; the
r6 INSENSITIVITY NOTE's "no exceptional set at all" was prosecuted as
riding F-1 and is now correctly re-typed). Grep of all esc_doc2 files
for "approximate limits ... exist": the phrase as a UNIVERSAL appears
first at r7; l0's C-3 confirmed the essential-type route on the
phantom witness only. No prior ID raises the existence claim.

------------------------------------------------------------------------------
**R4L1-3 — AMENDMENT. The r7 (⟸) re-read sources its third case from
"step (1)'s unconditional clause (1b)" — a statement DERIVED FROM
K = 0 in the forward proof — inside the direction whose GOAL is K = 0:
as cited, the without-pin (⟸) is circular. The direction is TRUE and
the pinned form closes independently (the sentence's own tail: "under
the r7 pin N_F is in any case front-null"), and a two-line pin-free
route exists from the (⟸) givens alone — but the printed primary
citation points the wrong way along the iff.**

Verbatim quote (2131–2142):

> "(⟸, re-read against the jump-set form, stays trivial — RE-RUN AT
> THE a.e. GRADE, r7, F-1: ... the direction never needed it: ∂_φ V =
> 0 kills every a.c. K row classically off fronts, and each front atom
> n_φ [F_φ,rel] dies AS A MEASURE because n_φ [F_φ,rel] = 0 H²-a.e. on
> each front — off the jump set [F_φ,rel] = 0 (equal pair limits +
> state-continuity of the fluxes); on the jump set minus N_F, n_φ = 0
> (containment); and on N_F ∩ {n_φ ≠ 0} the ESSENTIAL jump vanishes
> a.e. by step (1)'s unconditional clause (1b) — no nullness premise
> consumed; under the r7 pin N_F is in any case front-null.)"

Derivation-level attack. In (⟸) the given is the CONCLUSION (∂_φV = 0
+ containment + structure clauses) and the goal is K = 0. Cases 1 and
2 correctly consume givens (per-pair limit equality off the jump set;
the containment). Case 3 cites (1b) — but (1b) is an assembly-step
OUTPUT of the FORWARD proof: its derivation runs the case chains,
which consume "K = 0 forces the meridional RH" and the K = 0 atom
vanishing. Citing it as a premise while proving K = 0 is circular as
sourced. What saves the direction: (i) PINNED FORM (the form the
certification sentence names): the tail clause closes case 3 outright
— N_F front-null by the pin, so N_F ∩ {n_φ ≠ 0} is H²-null and the
measure argument needs nothing there; valid, non-circular. (ii)
WITHOUT-PIN FORM: the honest gloss the r7 conclusion itself prints
(1858–1860: "up to a closed set carrying no ESSENTIAL-jump mass on
{n_φ ≠ 0}") IS part of the given conclusion, and citing THAT (a given)
instead of (1b) (a forward step) closes case 3 legitimately. (iii)
Independently, a two-line pin-free derivation from the (⟸) givens
alone exists and is STRONGER than what is cited: ∂_φV = 0 gives
V = Ṽ∘π a.e.; the approximate-discontinuity set of an L¹ class is
L³-null (Lebesgue points) and here rotation-invariant, hence the lift
of an L²-NULL meridional set; on {n_φ ≠ 0} every front is locally a
graph φ = ψ(x, r) (n_φ ≠ 0 ⟺ locally solvable for φ), so its
intersection with that lift has H² ≍ L²(shadow) = 0 — essential jumps
of V, hence of the state-continuous flux F_φ,rel, are confined to an
H²-null subset of front ∩ {n_φ ≠ 0}, with no pin and no forward step
consumed. REPAIR (one phrase): replace "by step (1)'s unconditional
clause (1b)" with "by the conclusion's own without-pin gloss (no
essential-jump mass on {n_φ ≠ 0} — the statement step (1) derives as
(1b) in the forward direction), or directly: the approximate-
discontinuity set of the φ-independent class is the lift of an L²-null
meridional set, hence H²-null on the locally-graph strata
{n_φ ≠ 0}". Class: **AMENDMENT** (true conclusion, mis-directed
citation — the R3L1-4 species exactly; NOT REPAIR: the certified
pinned form closes via the pin tail printed in the same sentence, and
the mis-source is a one-phrase fix with two valid routes named).

NOVELTY/DEDUP: the r7 re-read sentence is wholly r7-minted (F-1(ii)
killed the r6 premise "N_F is front-null under the class pin"; the
substitute citation did not exist before r7). No prior ID raises a
direction-of-derivation defect in (⟸). The ROUND 4 residue paragraph's
"the distributional core ∂_φV = 0 and the ⟸ direction need no pin at
all — both now derived pin-free" (2984–2985) and the register row's
"(⟸) re-read re-run at a.e. grade, no nullness premise" inherit this
finding as riders (accurate on the repaired citation, not as printed).

==============================================================================
## §3 CONFIRMED passages (strongest attack tried, each)

**C-1. CLASS PIN restatement (p1)–(p3) + sufficiency derivation
(1806–1847) — CONFIRMED.** Strongest attack (new witness class): the
SINGLE-CONNECTED-FRONT variant of F-1's phantom witness — wire the
hovering C∞ graph G to F by a C¹ flap far from the accumulation zone,
declaring the union ONE connected C¹ hypersurface H accumulating on
ITSELF over the fat Cantor lift E; then (p1) is vacuous (no distinct
pair) and (p3) is vacuous ("accumulates on ANOTHER") — the fat N_F
would survive both. KILLED BY (p2): H is closed (E ⊂ F ⊂ H) but NOT
properly embedded at any point of E — manifold topology ≠ subspace
topology exactly there (G-sheet points are spatially close to q ∈ E
and manifold-far), so the proper-embedding failure set contains E with
H²(E) > 0 and NO H²-null edge set exists: out-of-pin, under either
reading of "up to". Second attack: the sufficiency line "can change
only where the closure of the remaining front set meets F or where
F's own edge is approached" tested against a front G disconnecting a
side region WITHOUT touching F — fails: if cl(G) ∩ F = ∅ the local
half-balls at F lie in the untouched slab of thickness
dist(cl(G), F) > 0, and the adjoining global pieces are locally
constant; adjacency is a germ property, so structure changes need
cl(other fronts) ∩ F or the (p2) failure set (which absorbs
self-accumulation, per the first attack). Third: the phantom-front
witness itself re-run — violates (p3) exactly as the ROUND 4 row
says. The pin now prices exactly what the chain consumes; the
rectifiability retraction (R3L1-2) is correctly merged (no
rectifiability claimed; "suffice WHERE they occur" is a true
sufficiency: H¹-rectifiable ⟹ H²-null).

**C-2. Conclusion "i.e." gloss re-derivation + without-pin honest
gloss (1848–1862) — CONFIRMED.** The "i.e." now claims exactly what
(p1)–(p3) buys (N_F front-null ⟹ containment = int{n_φ = 0} up to a
front-null set); the without-pin fallback "up to a closed set carrying
no ESSENTIAL-jump mass on {n_φ ≠ 0}" is exactly what (1b) delivers and
what the (⟸) direction can consume as a given. The R2L1-1 witness
re-run: null set exactly ∂P ⊂ N_F — passes. Attack tried: a gap
between "front-null" (per-front H²-null) and the global statement —
none: the containment is stated per front and N_F is per front.

**C-3. Grade-aligned structure clause (i) (1878–1882, derivation
2101–2120) — CONFIRMED at its stated grade.** Strongest attack: force
φ-DEPENDENT traces off N_F via shadow-limit mismatch — the trace at q
is the limit of the meridional representative along the piece's
shadow, and at a rotated q′ the approach shadow differs, so the two
limits could differ if the representative has no meridional limit.
KILLED in two steps, both carried by the printed ingredients: (a) the
piece-level lemma "a continuous function equal a.e. to a φ-independent
one on a connected open set is φ-independent" is TRUE by uniqueness of
continuous representatives (two local continuous versions of the same
L¹ class on overlapping meridional balls coincide — the winding-piece
counterexample dies); (b) off N_F the local complement is EXACTLY two
half-balls (no other fronts, no edge, no structure change — the pin's
own case analysis), so the piece contains a full one-sided collar of
the locally φ-invariant patch, the approach shadows at q and q′ are
the SAME meridional half-neighborhood (rotation-congruent via the
step-(2) product structure — "makes the one-sided traces
rotation-covariant" carries precisely this), and the (u1) extension
gives one limit, φ-independent. The honest surrender at patch ∩ N_F
("per-pair limits ... are not claimed") is exactly where my
construction attempts had lived; nothing flat survives to attack.

**C-4. Grade-aligned structure clause (ii) (1882–1889, derivation
2120–2129) — CONFIRMED.** Rotation-invariance of the essential jump
set is UNCONDITIONAL and correctly so: the essential jump set is an
invariant of the L¹ class, the class equals a φ-independent one, and
rotations are measure-preserving — a union of φ-circles. Attack tried:
an essential-jump circle escaping the product structure claim —
honestly excluded by the clause's own scoping ("where it meets a
front's int{n_φ = 0} stratum ... up to the same front-null N_F
geometry"); a circle INSIDE fat N_F is exactly what the r7 text no
longer claims to structure. No over-grade.

**C-5. Step-(1) grade separation (1a)/(1b) (2018–2033) — CONFIRMED as
to both clause grades (justification gloss = R4L1-2).** (1a): the case
chains run per-point where the pair persists and g ≠ 0; density of
{g ≠ 0} ∩ {n_φ ≠ 0} in the relatively open {n_φ ≠ 0} ∖ N_F plus
(u1)-continuity of [V] on F ∖ N_F upgrade to EVERYWHERE there — a.e.
as stated is weaker: delivered. Under the pin, a.e. on {n_φ ≠ 0}:
delivered (N_F null). (1b) at its stated content (essential jump set ∩
{n_φ ≠ 0} H²-null, no pin): delivered by the chains at essential-jump
points (limits exist there by definition; the K = 0 measure argument
supplies the essential flux RH a.e.; the RH algebra of both n_m cases
re-checked at essential type — the division by g and the H-CVX
n_m = 0 closure consume only trace values, indifferent to which limit
type supplied them). Attack on the SEPARATION itself: hunt a consumer
of (1a) at full-{n_φ ≠ 0} grade — none: step (3) consumes only (1b)
(verified at 2083–2084), the containment consumes (1a) only off N_F.

**C-6. (u1) written (2034–2047) — CONFIRMED.** The extension lemma
re-derived: for q_n → q on the front with the same pair adjoining,
pick p_n in-piece with |p_n − q_n| < 1/n and |V(p_n) − ext(q_n)| <
1/n; then p_n → q, so V(p_n) → ext(q) by the UNRESTRICTED one-sided
limit at q, hence ext(q_n) → ext(q) — the ε-argument as named.
Attack tried: does §0 grant "unrestricted" limits? §0's class is
values-limits at each front point with no approach restriction stated
— the reading R3L1-4 itself adjudicated; the r7 text consumes exactly
that grant and no more (the "C¹ up to the front" over-citation is
gone). The label collision with the UNCLAIMED upgrade half is R4L1-1,
not a content defect.

**C-7. Density parenthetical re-justification (2048–2054) —
CONFIRMED.** Exact: {n_φ ≠ 0} ∖ N_F is relatively open (N_F closed),
an H²-a.e.-full subset of a relatively open subset of a C¹ surface is
dense in it, and NO nullness of N_F is consumed — the r6 defect
(F-1(iii)) is repaired at its root, not patched.

**C-8. INSENSITIVITY NOTE r7 type clarification (2058–2066) —
CONFIRMED.** The note now says precisely what is true: the
distributional closure consumes clause (1b) only, at measure grade,
with no pin; N_F and per-pair grades affect only the displayed
pointwise geometry, priced there. Attack tried: a hidden consumer of
the per-pair grade inside step (3) — none (the atom's density is a
class object; per-pair data on density-0 slivers is invisible to it,
re-derived by per-piece integration by parts with telescoping through
interleaving jump-free sheets at density points).

**C-9. Step-(3) atom parenthetical re-typing (2080–2089) —
CONFIRMED.** "The atom is an H²-a.c. measure and sees only ESSENTIAL
jumps" — re-derived as a class statement: ∂_φV depends only on V's
L¹ class; a singular measure determined by the class cannot read
per-pair data invisible to approximate limits. The L0-5 normalization
deferral remains correctly un-consumed ("whatever the surface-measure
normalization"). No pin consumed — verified against the F-1(iv)
mechanism.

**C-10. (w1) exemplar re-scope (1588–1614) — CONFIRMED.** Strongest
attacks: (i) JOINT SATISFIABILITY — the pumping record certifies
∂_φp ≠ 0 SOMEWHERE off fronts, not inside the marching domain, so a
front-free subdomain compactly inside the marching domain MEETING the
pumping region might not exist — DISSOLVED: the r7 text prices exactly
this ("front-freeness and the pumping intersection are stated
HYPOTHESES of the instance, not derived"), and the appositive
"nonempty by the pumping record" reads on its sensible antecedent (the
D.19 pumping region — true of record); the witness role is in any case
independently carried by the full flow and (w2)/(α). (ii) MEMBERSHIP —
the restriction satisfies H-NC and H-WR trivially: on the compact
closure inside the marching domain, |w_rel| > c attains a positive
margin ([T-NSW](a) + continuity off fronts on a front-free subdomain),
so the sonic locus is EMPTY and w_rel ≠ 0 everywhere (c > 0 on the
compact closure); genuine φ-dependence is the stated hypothesis
∂_φV ≢ 0; the a.c. leg runs locally, so K ≠ 0 as a distribution on the
subdomain type-checks without a full S¹ fiber. (iii) the ∂_φp → ∂_φV
strengthening is sound (p is a state function of V; ∂_φp ≠ 0 forces
∂_φV ≢ 0). (iv) The r6 quotation and the three-generation history are
preserved verbatim, never erased. The fourth generation of the
exemplar spec finally carries its predicates as hypotheses — the
defect line is closed.

**C-11. G-f mixed-front RE-BIND (2621–2628) — CONFIRMED; F-4
DISCHARGED.** Re-derived on the instance: the mixed-front witness's
jump set is strictly inside the φ-invariant part of ONE connected
front (N_F = edge points only there), avoids N_F, so the r5 and
r6/r7 containments coincide on it — the falsifier-(d) note transcribed
into the executor-facing entry is exact, and the instruction
("transcribes the containment of record, never the retracted display")
removes the last executor path to the retracted form. Attack tried:
any OTHER G-f item still bound to a retracted display — grep: none
(the coincidence-boundary item binds to "the r6 containment"; the
azimuthal-sheet trigger to the connected-adiabat form; the r4
dichotomy display appears only as a REFUTE target, which is correct).

**C-12. Class/proof-state block: r7 certification + counter at FOUR
(2186–2231) — CONFIRMED (see §4 for the R-2 check).** The r6 sentence
is quoted in full and annotated REFUTED-as-printed with both
mechanisms (flat clauses; undelivered pin price); the counter
arithmetic r4/r5-header/r5/r6 = FOUR is right; the assembly-repair
count ("r7 the FOURTH") is right; annotate-never-erase verified at all
five r7 annotation sites (r6 pin, r6 clauses, r6 rider, r6
certification, r6 re-read — each preserved in quotation).

**C-13. Register row ROUND 4 clause (2562) + r7 annotation on the
ROUND 3 table (2940–2951) + ROUND 4 disposition table and residue
paragraph (2953–3010) — CONFIRMED as bookkeeping, with two riders.**
Fidelity checked row-against-file for all eight findings (both
round-3 files): each Item column matches its source objection 1:1;
each Disposition matches the landed text (spot-verified: (p3) kills
the phantom witness; the scoping option; the adopted F-3 phrase; the
(d)-note copy). The two declared prices (pin strengthened; clauses
weakened) are real and honestly stated; the downstream census ("S.22
identification and the G-f instances consume neither") verified. NO
label motion: both iff clauses at SCHEMA per J-r2p-2/J-r2p-3 at all
four sites; E-3 left to the escalation judge; layer/gate caveat
carried forward verbatim. Riders: the R3L1-1/R3L1-4 rows' "(u1)"
wording inherits R4L1-1; the residue paragraph's "both now derived
pin-free" inherits R4L1-3 — as at rounds 2 and 3, the rows stand as
enumerated with the residue riding this round's findings.

**C-14. Revision-log r7 block (183–227) — CONFIRMED.** The five
substance items match the body edits point-for-point; "All eight
objections verified correct ... consumed FIXED (no rebuttals)" matches
the table; the counter update and the labels-unchanged clause are
accurate.

**C-15. Leg-7 / A-1 (D.2 parenthetical) — CONFIRMED, no regression.**
Grep: no r7 marker below the header block touches D.2 (nearest body
marker: 1596); the judge's A-1 wording ("i.e. genuinely nonlinear WITH
the convex (compressive-shock) orientation") stands verbatim (~404–405)
with the false-equivalence mechanism recorded in-statement. Attack
tried: does the r7 pin restatement obligate D.2's front clauses (its
class of fronts) to carry (p1)–(p3)? No — D.2's front clauses are
per-front RH transport statements consuming no front-set global
geometry; the pin conditions only D.18's jump-set CONTAINMENT
apparatus. No cross-contamination.

==============================================================================
## §4 R-2 COUNTER CHECK (explicit, per the adjudication mandate:
##    "any fifth over-grade = REPAIR finding")

The r7 certification sentence — "the second iff, in its r7 form (...),
is proved under H-NC + H-WR (+ connected-adiabat H-CVX on the n_m = 0
strata) at the grades its clauses now carry IN-LINE" — was tested
clause-by-clause against the written derivation:

- containment (everywhere off N_F): delivered (density + (u1)
  continuity + closure step);
- nullness gloss (BY the pin): delivered ((p1)–(p3) sufficiency,
  C-1);
- clause (i) at "everywhere off N_F / H²-a.e. on the patch":
  delivered (C-3);
- clause (ii) at "rotation-invariance unconditional; product on
  int{n_φ = 0} strata up to N_F geometry": delivered (C-4);
- (1a)/(1b) at their stated grades: delivered (C-5);
- Ṽ ∈ C¹ off a closed rotation-invariant meridional set: unchanged
  from r6, re-verified standing.

**VERDICT: the r7 certification is NOT a fifth over-certification.**
All three findings of this round live in a label collision (R4L1-1), a
justification gloss (R4L1-2), and a citation's direction-of-derivation
(R4L1-3) — none is a clause printed above its derived grade, and none
touches a conclusion display. The counter of record STAYS at FOUR.

==============================================================================
## §5 Summary and dryness statement

| ID | Target (r7 passage) | Class |
|---|---|---|
| R4L1-1 | "(u1) ... NOT written and NOT claimed" (1874–1876) vs "(u1), hereby WRITTEN" (2037) + ROUND 4 adjacent rows — one label, two roles (R-4 pattern: transplanted name misfits the row) | AMENDMENT |
| R4L1-2 | clause (1b) justification's underived universal "approximate limits, which exist H²-a.e." (2029–2031) — unconsumed by (1b)'s own definitional quantification, by step (3)'s measure argument, or by (⟸) | AMENDMENT |
| R4L1-3 | (⟸) case 3 cites "step (1)'s unconditional clause (1b)" — a K = 0-derived forward step — inside the direction whose goal is K = 0 (2139–2141); pinned form closes via the pin tail; two valid pin-free citations named | AMENDMENT |

BREAKS-THE-LEG: 0. REPAIR-NEEDED: 0. Total findings: 3 AMENDMENT — the
first round of this leg's escalation loop with ZERO proof-content
repairs and zero false printed displays. Every conclusion clause,
every witness verdict, the pin sufficiency, the RH algebra of both
case chains at essential type, and the certification sentence itself
SURVIVED the strongest attacks I could construct (incl. one NEW witness
class: the single-connected-front self-accumulation variant, killed by
(p2)). The r7 disposition of all eight round-3 findings is verified
sound; A-1 stands. Under the documents' own dryness criterion (zero
sustained findings at both lenses) this lens does NOT return a dry
round — three one-edit amendments stand between the r7 text and dry —
but the residue class has now been label/gloss/citation hygiene for
two consecutive rounds with the mathematical core untouched, and no
finding here implies any label motion (both iff clauses stay at SCHEMA
per J-r2p-2/J-r2p-3; E-3 adjudication and the G-f battery remain the
restoration path).

==============================================================================
## §6 Self-falsifiers for THIS refutation

- R4L1-1 dies if the document is shown to define "(u1)" ONCE with both
  halves distinguished somewhere of record (grep found no such
  definition: the two occurrences at 1874 and 2037 are the only
  definitional-weight uses, and they point at different contents).
- R4L1-2 dies if (i) a written in-class proof of the existence
  universal is exhibited on file (my grep found only the sliver
  parenthetical), or (ii) the phrase is shown to be consumed by some
  step (then it would ESCALATE to repair, not die — the consumption
  map above says nothing consumes it), or (iii) my claim that
  essential-jump quantification makes it unnecessary is refuted by a
  consumer needing limits at NON-jump points (step (3) and (⟸) are
  measure-level; none found).
- R4L1-3 dies if "step (1)'s unconditional clause (1b)" is adjudicated
  to name the CONCLUSION's without-pin gloss rather than the assembly
  step (the printed words "step (1)'s ... clause" point at the
  assembly step; the gloss lives in the conclusion display), or if the
  (⟸) direction is shown NOT to have K = 0 as its goal (the proof
  header's "⟸ trivial — re-read against the jump-set form" fixes the
  direction: from the jump-set form TO K = 0).
- The §3 confirmations die by exhibiting an error in any recorded
  re-derivation, each reproducible: the (p2) embedding-failure kill of
  the self-accumulation witness; the germ/slab argument for structure
  changes; the continuous-representative uniqueness + half-ball shadow
  argument for clause (i); the ε-argument for (u1); the density-point
  sliver computation (Lipschitz-free version); the L³-null lift
  argument in R4L1-3(iii); the membership certificates of the (w1)
  restriction; the falsifier-(d) coincidence on the mixed-front
  witness; the A-1 grep.

Confirming-round lens-1 totals: 3 objections (0 B / 0 R / 3 A), 15
passages CONFIRMED with strongest attacks recorded, R-4 audit executed
on all eight repair clauses (two misfit instances found = R4L1-1 and
R4L1-3; one positive restatement instance recorded), R-2 counter check
executed (no fifth over-grade; counter stays at FOUR). Nothing else in
the r7 delta withstood less than the attacks listed.

END — machine summary: {breaks: 0, repairs: 0, amendments: 3,
file: validation/sfoundations_raws_2026-08-13/r2pass/esc_doc2_confirm_l1.md}
