#!/usr/bin/env python3
"""A1 [F3/A1] S41 2026-09-27: THE LIP JET of the two-wall march -- the free
jet after the shroud lip, gated against the plug march's own planar
simple-wave oracle. Registry ID: [X-LJET].

WHAT IS NEW. The two-wall (shrouded plug) march stopped at the lip's C-:
after F no top cell ran and the plug could not reach beyond the exit
characteristic. With plug_march(..., lip_jet=dict(qpa, n_fan, n_gl)) a
centred Prandtl-Meyer fan is inserted AT F (rays = rows of the lip column,
their states on the tabulated gas's simple-wave relation d theta =
sqrt(M^2 - 1) dq/q, a1_plug_march.pm_turn) from the lip speed to the ambient
speed, and every later column closes on the free-edge cell of the
single-wall march (make_resid_freejet): the internal-external nozzle.

THE ORACLE (planar, gconst tables). The plug march's own twin: uniform M1
meets the corner at the lip F with ambient p(M2); the exact field is
uniform M1, the centred fan at F, uniform M2 turned by dnu; the plug is the
EXACT streamline of that field (RK4, independent of any MOC). The march
starts UPSTREAM of the lip (uniform M1 between the plug and a horizontal
shroud ending at F): the fan is generated by the march, not given as data.
Gates, at two resolutions (Richardson bands, the oracle's own rules):
  L-0  the quadrature: pm_turn(q1, q2) = dnu of the closed form;
  L-1  every cell Newton-certified;
  L-2  the jet edge: its asymptotic angle -> dnu;
  L-3  the plug pressure matches the exact field at >= p2_frac_min of the
       stations;
  L-4  mass: the last column's flux = the start line's;
  L-5  momentum closes in the pa gauge (the free edge contributes zero);
  L-6  coverage: the jet march covers every plug station certified; the
       march WITHOUT the jet runs on past F's C- uncertified and misses the
       fan (measured: it does not stop there; its certificate is what keeps
       a no-jet record honest) -- the jet is load-bearing;
  R-1  rejector: a corrupted ambient speed leaves the L-2 band;
  R-2  rejector: the fan suppressed (n_fan 0 with an under-expanded lip)
       leaves the L-3 band.

Run:  .venv-a1/bin/python validation/a1_lipjet.py
"""
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import a1_ideal_march_jax as A1                                # noqa: E402
import a1_plug_march as PM                                     # noqa: E402
from a1_freejet_unit import q_at_pa                            # noqa: E402

import jax.numpy as jnp                                        # noqa: E402

EPS, K_RICH = A1.EPS, A1.K_RICH
HERE = os.path.dirname(os.path.abspath(__file__))
CASES = {k: v["value"] for k, v in json.load(open(os.path.join(HERE, "lipjet_cases.json"))).items()
         if not k.startswith("_")}
NPASS = [0, 0]


def check(label, ok):
    NPASS[0] += bool(ok)
    NPASS[1] += 1
    print("  [%s] %s" % ("PASS" if ok else "FAIL", label))
    return bool(ok)


def main():
    t0 = time.time()
    C = CASES["oracle"]
    print("== [F3/A1] the lip jet of the two-wall march against the planar simple-wave twin [X-LJET] ==")
    tg = A1.prep_tab(A1.build_tab_gconst())
    ta = A1.tab_arrays(tg)
    gam, Rg, ts = tg["_g"], tg["Rg"], tg["ts"]
    M1, M2 = C["M1"], C["M2"]
    dnu, field, q_of = PM.pm_exact(gam, Rg, ts, M1, M2)
    q1, q2 = q_of(M1), q_of(M2)
    pa = float(A1.state_q(jnp.float64(q2), ta)[1])
    qpa = q_at_pa(pa, ta, tg["_as"])
    lip = tuple(C["lip"])
    xs_, x_end, yp0 = C["x_start"], C["x_end"], C["y_plug0"]
    print("  M1 %.2f -> M2 %.2f at the lip (%.2f, %.2f): dnu %.6f rad; q1 %.4f, q2 %.4f (tables %.4f)"
          % (M1, M2, lip[0], lip[1], dnu, q1, q2, qpa))
    # L-0 the Prandtl-Meyer quadrature of the tabulated gas
    t1 = float(PM.pm_turn(jnp.float64(q1), jnp.float64(qpa), ta, C["n_gl"]))
    t2 = float(PM.pm_turn(jnp.float64(q1), jnp.float64(qpa), ta, 2 * C["n_gl"]))
    band0 = K_RICH * abs(t1 - t2) + A1.C_FLOOR * EPS * dnu
    check("L-0 pm_turn(q1, q_pa) %.10f = dnu %.10f of the closed form (|d| %.1e <= %.1e, the quadrature's own"
          " halving band + the table floor)" % (t1, dnu, abs(t1 - dnu), max(band0, abs(t2 - dnu) * K_RICH)),
          abs(t1 - dnu) <= max(band0, K_RICH * abs(t2 - dnu)))
    xs, ys = PM.exact_streamline(field, lip, (xs_, yp0), x_end, h=C["stream_h"])

    def run(K, N, nf, qpa_=qpa, jet=True):
        yline = np.linspace(yp0, lip[1], N)
        start = (xs_, yline, np.full(N, q1), np.zeros(N))
        tgrid = np.linspace(0, 1, K)
        sxa = xs_ + tgrid[1:] * (x_end - xs_)
        st = (jnp.array(sxa), jnp.array(np.interp(sxa, xs, ys)), jnp.array(np.interp(sxa, xs, np.gradient(ys, xs))))
        sxs = np.linspace(xs_, lip[0], C["n_shroud"])
        shr = (sxs, np.full(len(sxs), lip[1]), np.zeros(len(sxs)))
        lj = dict(qpa=qpa_, n_fan=nf, n_gl=C["n_gl"]) if jet else None
        out, S = PM.plug_march(st, start, qpa_, tg, 0.0, shroud=shr, lip_jet=lj)
        return out, S, sxa

    (Kc, Nc, fc), (Kf, Nf, ff) = C["rungs"]
    oc, Sc, sxc = run(Kc, Nc, fc)
    of, Sf, sxf = run(Kf, Nf, ff)
    print("  coarse K %d N %d fan %d: %d wall points, %d edge points, cert %.3f at %s; fine K %d N %d fan %d: %d / %d,"
          " cert %.3f at %s" % (Kc, Nc, fc, len(oc["wall"]), len(oc["edge"]), oc["cert_worst"], oc["cert_where"],
                                Kf, Nf, ff, len(of["wall"]), len(of["edge"]), of["cert_worst"], of["cert_where"]))
    check("L-1 every cell Newton-certified at both rungs (worst %.3f / %.3f)" % (oc["cert_worst"], of["cert_worst"]),
          oc["cert_worst"] <= 1.0 and of["cert_worst"] <= 1.0)

    def edge_stats(out):
        e = np.array(out["edge"])
        tail = e[int(C["tail_frac"] * e.shape[0]):]
        return float(np.arctan2(tail[:, 3], tail[:, 2]).mean()), float(np.hypot(tail[:, 2], tail[:, 3]).mean())
    thc, qec = edge_stats(oc)
    thf, qef = edge_stats(of)
    band_th = K_RICH * abs(thc - thf) + A1.C_FLOOR * EPS * abs(dnu)
    check("L-2 the jet edge: asymptotic angle %.6f -> dnu %.6f (|d| %.2e <= Richardson band %.2e); speed %.4f vs %.4f"
          % (thf, dnu, abs(thf - dnu), band_th, qef, q2), abs(thf - dnu) <= band_th)

    def wall_p(out):
        w = np.array(out["wall"])
        p = np.array(A1.state_q(jnp.array(np.hypot(w[:, 2], w[:, 3])), ta)[1])
        pex = np.array([float(A1.state_q(jnp.float64(field(w[k, 0], w[k, 1], lip)[0]), ta)[1]) for k in range(w.shape[0])])
        return w[:, 0], p, pex
    xwc, pc, pexc = wall_p(oc)
    xwf, pf, pexf = wall_p(of)
    pf_i = np.interp(xwc, xwf, pf)
    band_p = K_RICH * np.abs(pc - pf_i) + A1.C_FLOOR * EPS * pa
    dev = np.abs(pf_i - pexc)
    frac = float((dev <= band_p).mean())
    check("L-3 the plug pressure matches the exact field: %.0f %% of %d stations in the Richardson band (>= %.0f %%;"
          " max |dev|/pa %.2e)" % (100 * frac, len(xwc), 100 * C["p2_frac_min"], dev.max() / pa), frac >= C["p2_frac_min"])
    # L-4 / L-5: mass and momentum through the last column (uniform start)
    stline = np.stack([np.full(Nf, xs_), np.linspace(yp0, lip[1], Nf), np.full(Nf, q1), np.zeros(Nf)], axis=1)
    md0, Fin = PM.col_fluxes(stline, ta, pa, 0.0)

    def closures(out):
        md, Fout = PM.col_fluxes(np.array(out["last_col"]), ta, pa, 0.0)
        push_w = PM.wall_push_poly(np.vstack([stline[:1], np.array(out["wall"])]), ta, pa, 0.0)
        push_s = PM.wall_push_poly(np.vstack([stline[-1:], np.array(out["shroud"])]), ta, pa, 0.0)
        return md, Fout - Fin + push_w - push_s
    mdc, Rc = closures(oc)
    mdf, Rf = closures(of)
    band_m = K_RICH * abs(mdc - mdf) + A1.C_FLOOR * EPS * abs(md0)
    check("L-4 mass: last column %.8f vs start %.8f (|d| %.2e <= %.2e)" % (mdf, md0, abs(mdf - md0), band_m),
          abs(mdf - md0) <= band_m)
    band_F = K_RICH * abs(Rc - Rf) + A1.C_FLOOR * EPS * abs(Fin)
    check("L-5 momentum closes in the pa gauge, the free edge contributing zero: %.3e (coarse %.3e) <= %.3e on F_in %.4f"
          % (Rf, Rc, band_F, Fin), abs(Rf) <= band_F)
    # L-6: without the jet the march runs on past F's C- WITHOUT a top cell
    # (measured 2026-09-27: it does not stop there, as its docstring said):
    # beyond the point where F's first ray meets the plug its cells are not
    # certified and its plug pressure misses the fan -- the jet is load-
    # bearing, and the certificate is what keeps a no-jet record honest
    on, _, _ = run(Kf, Nf, ff, jet=False)
    xwn, pn, pexn = wall_p(on)
    x_hit = lip[0] + (lip[1] - yp0) / np.tan(np.arcsin(1 / M1))
    beyond = xwn > x_hit
    dev_n = float(np.max(np.abs(pn[beyond] - pexn[beyond])) / pa) if beyond.any() else 0.0
    check("L-6 coverage: the jet march covers all %d plug stations certified; the march WITHOUT the jet past F's"
          " first ray (x %.3f) is uncertified (cert %.1e) and misses the fan (max |dp|/pa %.2f against %.2e with"
          " the jet)" % (len(sxf), x_hit, on["cert_worst"], dev_n, dev.max() / pa),
          len(of["wall"]) == len(sxf) and of["cert_worst"] <= 1.0 and on["cert_worst"] > 1.0
          and dev_n > dev.max() / pa)
    ob, _, _ = run(Kf, Nf, ff, qpa_=qpa * C["rej_qpa_factor"])
    thb, _ = edge_stats(ob)
    check("R-1 REJECTOR: the ambient speed corrupted by %.0f %% moves the edge to %.6f (|d| %.2e > band %.2e)"
          % (100 * (C["rej_qpa_factor"] - 1), thb, abs(thb - dnu), band_th), abs(thb - dnu) > band_th)
    try:
        o0, _, _ = run(Kf, Nf, 0)
        xw0, p0_, pex0 = wall_p(o0)
        frac0 = float((np.abs(np.interp(xwc, xw0, p0_) - pexc) <= band_p).mean())
        check("R-2 REJECTOR: the fan suppressed (n_fan 0, the lip under-expanded) leaves the L-3 band: %.0f %% of"
              " stations in band" % (100 * frac0), frac0 < C["p2_frac_min"])
    except Exception as e:                                     # a failed march is a rejection too
        check("R-2 REJECTOR: the fan suppressed -> the march fails (%s)" % type(e).__name__, True)
    print("  %d/%d PASS in %.0f s" % (NPASS[0], NPASS[1], time.time() - t0))
    return 0 if NPASS[0] == NPASS[1] else 1


if __name__ == "__main__":
    sys.exit(main())
