#!/usr/bin/env python
"""progress_counts.py — the PROGRESS ORA numbers GENERATED BY COMMAND (SR-12),
never typed. S-REVIEW lever F3 (2026-09-05). Prints one measured block that
the R3 close pastes into docs/rde_nozzle_PROGRESS.md ORA / the session log.

Counts (each with the command it reproduces):
  findings: total / OPEN by path (critical / non-critical / paper) / status
  choice ledger: rows by status
  claims: total / open-class (SCHEMA|CONJECTURE) / FAILING carriers (fail=)
  BLOCCATO rows (+ path: critical) from PROGRESS
  ADVISORY_INDEX: file rows / block rows
  literature registry rows
  git: HEAD short hash, commit count, branch
  env fingerprint (tests/test_claims_lint.env_fingerprint)
  roadmap: steps / overrides / OUT (from the derived doc header line)

Exit 0 always (a reporter, not a gate); --json for machine use. Self-test:
--selftest asserts the parsers on a seeded fixture (rejector: a row without
`path:` is counted as such, never silently dropped).
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _read(rel):
    with open(os.path.join(ROOT, rel), encoding='utf-8') as f:
        return f.read()


def findings():
    t = _read('docs/findings_registry.yaml')
    rows = re.split(r'\n(?=- id: )', t)
    rows = [r for r in rows if r.lstrip().startswith('- id: ')]
    out = dict(total=len(rows), status={}, open_by_path={}, open_no_path=0)
    for r in rows:
        st = re.search(r'^\s+status:\s*(\S+)', r, re.M)
        st = st.group(1) if st else 'MISSING'
        out['status'][st] = out['status'].get(st, 0) + 1
        if st in ('CONFIRMED', 'DOWNGRADED'):
            p = re.search(r'^\s+path:\s*(\S+)', r, re.M)
            if p:
                out['open_by_path'][p.group(1)] = out['open_by_path'].get(p.group(1), 0) + 1
            else:
                out['open_no_path'] += 1
    out['open_total'] = sum(out['open_by_path'].values()) + out['open_no_path']
    return out


def ledger():
    t = _read('docs/choice_ledger.yaml')
    rows = [r for r in re.split(r'\n(?=- id: C\d)', t) if r.lstrip().startswith('- id: C')]
    st = {}
    for r in rows:
        m = re.search(r'^\s+status:\s*"?([A-Z-]+)"?', r, re.M)
        k = m.group(1) if m else 'MISSING'
        st[k] = st.get(k, 0) + 1
    return dict(total=len(rows), status=st)


def claims():
    t = _read('docs/claims_registry.yaml')
    rows = [r for r in re.split(r'\n(?=- id: )', t) if r.lstrip().startswith('- id: ')]
    open_class = sum(1 for r in rows if re.search(r'^\s+class:\s*(SCHEMA|CONJECTURE)\b', r, re.M))
    failing = [re.match(r'- id:\s*(\S+)', r.lstrip()).group(1) for r in rows
               if re.search(r'ondemand:.*; fail=\d{4}-\d{2}-\d{2}', r)]
    return dict(total=len(rows), open_class=open_class, failing=failing)


def bloccato():
    t = _read('docs/rde_nozzle_PROGRESS.md')
    sec = t.split('## BLOCCATO')[1].split('\n## ')[0]
    rows = [l for l in sec.splitlines() if l.startswith('| B') or l.startswith('| B-')]
    crit = [l for l in rows if '| critical |' in l]
    return dict(total=len(rows), critical=len(crit),
                critical_ids=[l.split('|')[1].strip() for l in crit])


def index():
    t = _read('validation/ADVISORY_INDEX.md')
    lines = [l for l in t.splitlines() if l.startswith('| ') and not l.startswith('| ---')]
    file_rows = [l for l in lines if re.match(r'\| [A-Za-z0-9_./-]+\.(md|py|json|txt|patch|log|pdf)\s*\|', l)]
    block_rows = [l for l in lines if l not in file_rows and not l.startswith('| file') and not l.startswith('| ---')]
    return dict(file_rows=len(file_rows), block_rows=len(block_rows))


def literature():
    t = _read('docs/literature_registry.yaml')
    return dict(rows=len(re.findall(r'^- id: ', t, re.M)))


def git():
    def run(*a):
        return subprocess.run(['git'] + list(a), cwd=ROOT, capture_output=True, text=True).stdout.strip()
    return dict(head=run('rev-parse', '--short', 'HEAD'), commits=int(run('rev-list', '--count', 'HEAD') or 0),
                branch=run('rev-parse', '--abbrev-ref', 'HEAD'))


def envfp():
    sys.path.insert(0, os.path.join(ROOT, 'tests'))
    try:
        import test_claims_lint as t
        return t.env_fingerprint()
    except Exception as e:  # pragma: no cover
        return 'unavailable: %s' % e


def roadmap():
    """Parsed from the derived doc's own section 7 'Counts (measured by this
    tool)' + the step table of section 1 (never regenerates the doc)."""
    t = _read('docs/ROADMAP_critical_path.md')
    sec1 = t.split('## 1. ')[1].split('\n## ')[0]
    steps = len([l for l in sec1.splitlines() if l.startswith('| **')])
    sec7 = t.split('## 7. ')[1] if '## 7. ' in t else ''
    ovr = re.search(r'overrides\s+(\d+)', sec7)
    out = re.search(r'OUT\s+(\d+)', sec7)
    opn = re.search(r'OPEN findings\s+(\d+)\s*\(critical\s+(\d+)', sec7)
    return dict(steps=steps, overrides=int(ovr.group(1)) if ovr else None,
                out=int(out.group(1)) if out else None,
                open_findings=int(opn.group(1)) if opn else None,
                open_critical=int(opn.group(2)) if opn else None)


def collect():
    return dict(findings=findings(), ledger=ledger(), claims=claims(), bloccato=bloccato(),
                index=index(), literature=literature(), git=git(), envfp=envfp(), roadmap=roadmap())


def render(d):
    f, l, c, b = d['findings'], d['ledger'], d['claims'], d['bloccato']
    ob = f['open_by_path']
    lines = [
        '== PROGRESS COUNTS (generated by tools/progress_counts.py, SR-12) ==',
        'findings %d total; OPEN %d = %d critical / %d non-critical / %d paper (no-path %d); status %s'
        % (f['total'], f['open_total'], ob.get('critical', 0), ob.get('non-critical', 0), ob.get('paper', 0),
           f['open_no_path'], json.dumps(f['status'], sort_keys=True)),
        'choice ledger %d = %s' % (l['total'], ' / '.join('%d %s' % (v, k) for k, v in sorted(l['status'].items()))),
        'claims %d (%d open-class SCHEMA/CONJECTURE); FAILING carriers (fail=): %s'
        % (c['total'], c['open_class'], ', '.join(c['failing']) or 'none'),
        'BLOCCATO %d [%d critical: %s]' % (b['total'], b['critical'], ', '.join(b['critical_ids'])),
        'ADVISORY_INDEX %d file rows / %d block rows; literature registry %d rows'
        % (d['index']['file_rows'], d['index']['block_rows'], d['literature']['rows']),
        'git HEAD %s, %d commits, branch %s; envfp %s' % (d['git']['head'], d['git']['commits'], d['git']['branch'], d['envfp']),
        'roadmap %s' % json.dumps(d['roadmap']),
    ]
    return '\n'.join(lines)


def selftest():
    import tempfile
    fx = ("- id: a\n  status: CONFIRMED\n  path: critical\n- id: b\n  status: CONFIRMED\n"
          "- id: c\n  status: DISCHARGED\n  path: paper\n")
    rows = [r for r in re.split(r'\n(?=- id: )', fx) if r.lstrip().startswith('- id: ')]
    open_no_path = sum(1 for r in rows if re.search(r'^\s+status:\s*CONFIRMED', r, re.M)
                       and not re.search(r'^\s+path:', r, re.M))
    ok = (len(rows) == 3 and open_no_path == 1)
    print('selftest: 3 rows, 1 OPEN row without path counted as such (rejector) ->', 'PASS' if ok else 'FAIL')
    return 0 if ok else 1


if __name__ == '__main__':
    if '--selftest' in sys.argv:
        sys.exit(selftest())
    d = collect()
    if '--json' in sys.argv:
        print(json.dumps(d, indent=1, sort_keys=True))
    else:
        print(render(d))
